//! Night Drop security core.
//!
//! Everything security-critical lives here (see `ARCHITECTURE.md` §2 "golden rule"):
//! identity keys, the Double Ratchet, the PAKE bouncer, the Tor transport, the relay
//! client, and at-rest encryption. The Flutter app is a thin UI shell that calls into
//! this crate via the high-level surface in [`api`].

pub mod api;
mod lifecycle;
mod node;

// Generated by flutter_rust_bridge codegen (`flutter_rust_bridge_codegen generate`).
mod frb_generated;

pub mod crypto;
pub mod diag;
pub mod directory;
pub mod identity;
pub mod pake;
pub mod pqkem;
pub mod relay_client;
pub mod storage;
pub mod transport;
pub mod wire;

/// Crate-wide result type. The FFI surface in [`api`] converts these to messages the
/// UI can show; raw key material must never appear in an error string.
pub type Result<T> = anyhow::Result<T>;

/// Default per-chat display name for both parties (`ARCHITECTURE.md` §4).
pub const DEFAULT_NAME: &str = "Anon";
