//! Update check (`ARCHITECTURE.md` §10a): ask **our own onion site** whether a newer release
//! exists, over Tor, and tell the user — and, if the user asks for it, fetch that build and verify
//! it. Nothing here **installs** anything, and nothing downloads without the user saying so.
//!
//! ## Why this exists
//!
//! The Android build comes from F-Droid and updates itself. The **AppImage does not** — it is a
//! file on disk, and a user who downloaded one in 2026-08 is still running it today unless they
//! went looking. That is how a stale download link left people on 0.1.15 without the onion-identity
//! fix for three days (`docs/advisories/2026-08-05-linux-download-pinned-to-0.1.15.md`). A user who
//! cannot tell they are running a superseded build cannot act on a security fix.
//!
//! ## What it must not become
//!
//! An update check is a beacon, and this is a privacy tool, so the shape is deliberately the
//! smallest one that works:
//!
//! * **Over Tor, to an onion, always.** [`Transport::onion_get`] has no clearnet path; a transport
//!   that cannot fetch anonymously returns `None` and we skip the check entirely rather than
//!   reaching for anything else (§6, and the ClosedTransport DNS leak that taught us to say so).
//! * **The request carries nothing.** A plain `GET` of one static file, no version, no identifier,
//!   no cookie, no varying header. The server cannot distinguish one user from another, or a
//!   first check from a hundredth — it sees an anonymous request for a public file, which is what
//!   any visitor to the site makes. The comparison happens **here**, on the device.
//! * **It answers a question, it does not act.** The check returns a struct; the UI shows a
//!   notice; the user chooses. Nothing is fetched as a result of the check itself, and nothing is
//!   ever executed. [`download`] runs only on an explicit tap, writes only after the published
//!   hash matches, and hands the file to the user — Android decides what may replace this app.
//! * **Failure is silence.** The site being down, Tor being slow, or the JSON being malformed are
//!   all "no answer", never a warning. A user must not learn to dismiss update warnings.
//!
//! The onion address self-authenticates — a v3 `.onion` *is* an ed25519 public key, so reaching
//! it proves we reached the site and not an impostor, with no certificate authority involved.

use serde::Deserialize;

use crate::transport::Transport;
use crate::Result;

/// Our onion site, which serves [`MANIFEST_PATH`]. Baked in rather than configurable: an
/// attacker who could point the update check somewhere else could tell a user they are up to
/// date forever.
///
/// **This address is permanent.** It ships inside released binaries, so it cannot be changed for
/// anyone already running one — losing the service key would strand every install's update check
/// with no way to fix it from our side. Back the key up like the relay's (`RELAYS.md`).
pub const UPDATE_ONION: &str = "z6xw2ywlybjeskki4jons5ujepc2pedp5qkgvtbyxorie46qnjpnzqqd.onion";

/// The virtual port the onion site serves HTTP on.
pub const UPDATE_PORT: u16 = 80;

/// The static file holding the current release. Generated by `make config` from
/// `app/pubspec.yaml`, so the published version cannot drift from the released one.
pub const MANIFEST_PATH: &str = "/update.json";

/// Cap on reaching the site for the manifest. Far larger than it "should" need, for the reason
/// measured on the relay watchdog the same day: onion connect latency on a healthy network ranged
/// 3.4s to 56.8s, and a cold start can exceed even that. A tight cap here does not fail faster in
/// any useful sense — it just turns a slow circuit into "no update exists", which is the one
/// answer this feature must never give wrongly.
pub const FETCH_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(180);

/// Cap on downloading a build. Tens of megabytes over Tor is genuinely slow; this is a stop for a
/// hung transfer, not a performance target.
pub const DOWNLOAD_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(20 * 60);

/// Hard cap on a downloaded build. Comfortably above a real APK (~45 MB) and far below
/// anything that would hurt: a cap is what stops a hostile or broken server streaming until the
/// device runs out of storage.
pub const MAX_DOWNLOAD_BYTES: usize = 200 * 1024 * 1024;

/// Hard cap on the manifest. It is a handful of bytes of JSON; anything larger is not ours, and
/// an unbounded read from a remote host is how a small feature becomes an OOM.
pub const MAX_MANIFEST_BYTES: usize = 8 * 1024;

/// One downloadable build, as published for a specific Android ABI.
#[derive(Debug, Clone, Deserialize)]
pub struct UpdateDownload {
    /// Path on the onion site. A path, not a URL: there is nowhere else it may point.
    pub url: String,
    /// SHA-256 of the exact bytes served. Generated from the file itself
    /// (`scripts/gen-update-manifest.sh`), so it cannot drift from what is downloaded.
    pub sha256: String,
}

/// What the onion site publishes.
#[derive(Debug, Deserialize)]
pub struct UpdateManifest {
    /// The current release, as a bare `MAJOR.MINOR.PATCH` string.
    pub latest: String,
    /// Per-ABI downloads, when the site is serving any. Absent is normal and means "there is a
    /// newer version, but no download to offer" — tell the user, promise nothing.
    #[serde(default)]
    pub android: std::collections::HashMap<String, UpdateDownload>,
}

/// The answer for the UI.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UpdateStatus {
    /// What this build is.
    pub current: String,
    /// What the site says is current.
    pub latest: String,
    /// Whether `latest` is strictly newer than `current`.
    pub update_available: bool,
}

/// Ask the onion site what the current release is and compare it with `current_version`.
///
/// `current_version` accepts the pubspec form (`"0.1.17+403"`); the build metadata is ignored.
/// Returns `Ok(None)` when the transport cannot fetch anonymously — the caller does nothing.
pub fn check(transport: &dyn Transport, current_version: &str) -> Result<Option<UpdateStatus>> {
    // Started before the fetch, not after: `onion_get` blocks for the whole Tor round trip, so a
    // timer set on the line below would measure the JSON parse and report a 22µs network fetch.
    let started = std::time::Instant::now();
    let Some(fetched) = transport.onion_get(UPDATE_ONION, UPDATE_PORT, MANIFEST_PATH) else {
        // Not an error: this transport has no anonymized path, so there is no check to make.
        crate::diag!("update: no anonymized path on this transport — check skipped");
        return Ok(None);
    };
    let body = match fetched {
        Ok(b) => b,
        Err(e) => {
            // The failure the UI must not round off to "up to date". Timings matter here: onion
            // connect latency is the usual cause and is measured in tens of seconds.
            crate::diag!("update: check FAILED after {:?}: {e}", started.elapsed());
            return Err(e);
        }
    };
    let manifest: UpdateManifest = match serde_json::from_slice(&body) {
        Ok(m) => m,
        Err(e) => {
            crate::diag!(
                "update: manifest unparseable ({} bytes after {:?}): {e}",
                body.len(),
                started.elapsed()
            );
            return Err(e.into());
        }
    };
    let status = compare(current_version, &manifest.latest);
    crate::diag!(
        "update: site says {}, running {} -> {} (in {:?}, {} build(s) published)",
        status.latest,
        status.current,
        if status.update_available {
            "UPDATE AVAILABLE"
        } else {
            "up to date"
        },
        started.elapsed(),
        manifest.android.len()
    );
    Ok(Some(status))
}

/// Which published build belongs on **this** device.
///
/// Taken from the architecture this copy of the core was compiled for, which is the most reliable
/// signal available: Android picked one ABI's native library at install time, and this *is* that
/// library asking.
///
/// It must not be the universal build, even though one file running everywhere is tempting.
/// `--split-per-abi` gives the per-ABI APKs a versionCode of `base*10 + abi` (4031/4032/4033)
/// while the universal one keeps the bare base (403), so handing the universal APK to anyone
/// running a per-ABI install is a **downgrade by versionCode** and Android refuses to install it.
/// F-Droid ships per-ABI, so that is most users: they would wait out the whole download and then
/// be told "App not installed". The per-ABI build is also less than half the size, which over Tor
/// is the difference between a slow download and one that risks [`DOWNLOAD_TIMEOUT`].
///
/// **It does cost one bit of distinguishability**, and that is a deliberate trade rather than an
/// oversight: the download path now tells the site which of the published ABIs this device runs.
/// It is accepted because the thing that must not become a beacon is the *recurring* check, which
/// is unchanged and still byte-identical for every install (see
/// `the_request_is_identical_for_every_install`). A download is rare, user-initiated, and already
/// tells the site far more by simply happening. The alternative — a build that cannot install —
/// is not a privacy win.
pub fn native_abi() -> &'static str {
    match std::env::consts::ARCH {
        "aarch64" => "arm64-v8a",
        "arm" => "armeabi-v7a",
        "x86_64" => "x86_64",
        "x86" => "x86",
        // Not an Android ABI name; no entry will match and the download reports that honestly
        // rather than fetching a build for the wrong machine.
        other => other,
    }
}

/// Download the build for `abi` over Tor and write it to `dest`, but **only** if its SHA-256
/// matches what the manifest published.
///
/// The write happens after verification, never during: a file that exists is a file the user may
/// be about to install, so a partial or wrong download must never reach that path. Returns the
/// number of bytes written.
///
/// This does not install anything, and deliberately cannot. Android verifies the signature itself
/// and will refuse to replace Night Drop with anything not signed by our release key — so the
/// worst a compromised site can do is waste the download, not swap the app.
/// `on_progress` is called as the transfer runs, throttled to [`UI_PROGRESS_INTERVAL`], with
/// `(bytes_so_far, content_length)`. It exists so the UI can show a real bar; the same numbers go
/// to the log on a slower cadence.
pub fn download(
    transport: &dyn Transport,
    manifest: &UpdateManifest,
    abi: &str,
    dest: &std::path::Path,
    on_progress: &dyn Fn(u64, Option<u64>),
) -> Result<u64> {
    let Some(entry) = manifest.android.get(abi) else {
        // Names the ABI, because the failure is silent otherwise and the answer is always "the
        // manifest does not publish the one this device needs".
        crate::diag!(
            "update: download ABORTED — no published build for {abi} (site offers: {})",
            abi_list(manifest)
        );
        anyhow::bail!("no published build for {abi}");
    };
    crate::diag!("update: downloading the {abi} build");
    let started = std::time::Instant::now();
    // Streamed here, never to `dest`. `dest` is the path the caller will make reachable, so a file
    // must not appear there until it has passed — and the scratch name is what makes that possible
    // without holding the whole build in memory.
    // A stable, hash-keyed slot rather than a name unique per attempt: resuming needs to find
    // what the last attempt left. Two downloads must still never share it, which is why
    // `NightdropCore::download_update` is single-flight — that guard is now load-bearing rather
    // than defence in depth.
    let part = part_path(dest, &entry.sha256);
    sweep_stale_parts(dest, &part);
    let resume_from = std::fs::metadata(&part).map(|m| m.len()).unwrap_or(0);
    if resume_from > 0 {
        crate::diag!("update: resuming from {resume_from} bytes already on disk");
    }
    // Throttled here rather than in the transport: at a 16KiB chunk this fires ~2,800 times for a
    // 45MB build, and a log line per chunk is not observability. A stall produces silence rather
    // than a line — but the last line printed then says how far it got and when, which is the
    // question being asked.
    let last_log = std::cell::Cell::new(std::time::Instant::now());
    let last_ui = std::cell::Cell::new(std::time::Instant::now());
    let progress = |done: u64, total: Option<u64>| {
        if last_log.get().elapsed() >= PROGRESS_INTERVAL {
            last_log.set(std::time::Instant::now());
            match total {
                Some(t) if t > 0 => {
                    crate::diag!("update: {done}/{t} bytes ({}%)", done * 100 / t)
                }
                _ => crate::diag!("update: {done} bytes so far"),
            }
        }
        // Separate cadence: the log wants a readable handful of lines, the UI wants a bar that
        // moves. Same source, so they can never disagree about how far along it is.
        if last_ui.get().elapsed() >= UI_PROGRESS_INTERVAL {
            last_ui.set(std::time::Instant::now());
            on_progress(done, total);
        }
    };
    let Some(fetched) = transport.onion_get_to_file(
        crate::transport::FileFetch {
            onion: UPDATE_ONION,
            port: UPDATE_PORT,
            path: &entry.url,
            dest: &part,
            max_bytes: MAX_DOWNLOAD_BYTES as u64,
            resume_from,
        },
        &progress,
    ) else {
        crate::diag!("update: download ABORTED — transport cannot fetch anonymously");
        anyhow::bail!("this transport cannot fetch anonymously");
    };
    let n = match fetched {
        Ok(n) => n,
        Err(e) => {
            // Where a Doze freeze or a dead circuit shows up. The elapsed time is the whole point:
            // it separates "the network stalled" from "we hit DOWNLOAD_TIMEOUT".
            // The partial stays: a failed 40MB transfer over Tor is worth resuming, and the
            // final hash is what decides whether the assembled bytes are acceptable, so keeping
            // them costs nothing but disk.
            let kept = std::fs::metadata(&part).map(|m| m.len()).unwrap_or(0);
            crate::diag!(
                "update: download FAILED after {:?} ({kept} bytes kept to resume from): {e}",
                started.elapsed()
            );
            return Err(e);
        }
    };
    let fetched_in = started.elapsed();

    // Hashed by reading the file back, not from a buffer we still hold — that is the whole point
    // of streaming, and it also verifies what actually reached the disk rather than what we
    // believe we wrote.
    let got = match sha256_file(&part) {
        Ok(h) => h,
        Err(e) => {
            crate::diag!("update: could not read back the downloaded build: {e}");
            let _ = std::fs::remove_file(&part);
            return Err(e);
        }
    };
    if !got.eq_ignore_ascii_case(entry.sha256.trim()) {
        // Not "corrupt download, retry". We asked an authenticated onion for a file it told us
        // the hash of; a mismatch means something is wrong that a retry will not fix. The partial
        // goes with it — resuming into the same bad result forever is worse than starting over.
        crate::diag!("update: HASH MISMATCH on {n} bytes after {fetched_in:?} — discarded");
        let _ = std::fs::remove_file(&part);
        anyhow::bail!(
            "downloaded build did not match the published hash (expected {}, got {got})",
            entry.sha256
        );
    }
    // Only now does a file appear at `dest`. Rename is atomic within a filesystem, so there is no
    // instant where a partial build is visible under the final name.
    if let Err(e) = std::fs::rename(&part, dest) {
        crate::diag!("update: verified {n} bytes but could not place the file: {e}");
        let _ = std::fs::remove_file(&part);
        return Err(e.into());
    }
    crate::diag!("update: {n} bytes verified and written in {fetched_in:?}");
    Ok(n)
}

/// The numeric status from a response head's first line.
fn parse_status(head: &[u8]) -> Result<u16> {
    let head = std::str::from_utf8(head)
        .map_err(|_| anyhow::anyhow!("update: response headers were not text"))?;
    let status = head.lines().next().unwrap_or_default();
    status
        .split_whitespace()
        .nth(1)
        .and_then(|c| c.parse().ok())
        .ok_or_else(|| anyhow::anyhow!("update: unexpected status line {status:?}"))
}

/// Pull `Content-Length` out of a response head. Case-insensitive on the field name, as HTTP
/// requires; absent or unparseable simply means progress has no denominator, which is a worse
/// log line and nothing more.
fn parse_content_length(head: &[u8]) -> Option<u64> {
    let head = std::str::from_utf8(head).ok()?;
    head.lines()
        .filter_map(|line| line.split_once(':'))
        .find(|(name, _)| name.trim().eq_ignore_ascii_case("content-length"))
        .and_then(|(_, value)| value.trim().parse().ok())
}

/// How often a running download writes a progress line to the log. Long enough that a
/// multi-minute transfer produces a readable handful of lines rather than thousands, short enough
/// to localise a stall.
const PROGRESS_INTERVAL: std::time::Duration = std::time::Duration::from_secs(15);

/// How often a running download tells the **UI** where it has got to. Much faster than the log
/// cadence — a progress bar that moves four times a minute reads as broken — but still throttled,
/// because each one crosses the FFI boundary and wakes the Dart side.
const UI_PROGRESS_INTERVAL: std::time::Duration = std::time::Duration::from_millis(400);

/// Incremental parser for a streamed response head.
///
/// [`body_of`] can read the whole response and split it once; a streamed download cannot, because
/// the body is precisely the thing that must never be fully resident. This buffers only up to the
/// `\r\n\r\n` terminator, validates the status line through the same [`body_of`] check, and from
/// then on hands chunks straight through.
///
/// Lives here rather than in the transport so it can be tested against arbitrary chunk boundaries
/// — including a terminator split across two reads, which is otherwise reachable only with a live
/// Tor circuit and the right packet timing.
#[derive(Default)]
pub struct ResponseHead {
    head: Vec<u8>,
    done: bool,
    content_length: Option<u64>,
    status: u16,
}

impl ResponseHead {
    /// Feed one chunk as read from the wire; returns the portion of it that is body, which is
    /// empty while the head is still arriving.
    pub fn push<'a>(&mut self, chunk: &'a [u8]) -> Result<&'a [u8]> {
        if self.done {
            return Ok(chunk);
        }
        self.head.extend_from_slice(chunk);
        let Some(end) = self.head.windows(4).position(|w| w == b"\r\n\r\n") else {
            // Bound the head too: a server that never terminates it would otherwise grow this
            // buffer without limit, which is the same unbounded-read bug in a different place.
            if self.head.len() > MAX_MANIFEST_BYTES {
                anyhow::bail!("update: response head had no terminator");
            }
            return Ok(&[]);
        };
        // 200, or 206 when we asked to resume from an offset. Anything else is not a body we will
        // write to disk — a 404 page must never land where a build is expected, and only the hash
        // would catch it afterwards.
        self.status = parse_status(&self.head[..end])?;
        if self.status != 200 && self.status != 206 {
            anyhow::bail!("update: unexpected status {}", self.status);
        }
        self.content_length = parse_content_length(&self.head[..end]);
        self.done = true;
        // The body bytes sit at the tail of both buffers. At least one byte of the terminator must
        // have arrived in *this* chunk (otherwise it would have been found on an earlier push), so
        // this can never exceed the chunk; min() keeps that a wrong answer rather than a panic if
        // the invariant is ever broken.
        let consumed = (self.head.len() - (end + 4)).min(chunk.len());
        Ok(&chunk[chunk.len() - consumed..])
    }

    /// `Content-Length`, once the head has been seen. Advisory only — it is what the server
    /// *claims*, so it may be used to report progress but never to decide the download is
    /// complete or correct. The published SHA-256 is the only thing that settles that.
    pub fn content_length(&self) -> Option<u64> {
        self.content_length
    }

    /// The response status, once the head has been seen. 206 means the server honoured a Range
    /// request and the body continues an existing file; 200 means it ignored the range and is
    /// sending the whole thing, so anything already on disk must be thrown away.
    pub fn status(&self) -> u16 {
        self.status
    }

    /// Whether a complete head was seen. A stream that ends before this did not deliver a response.
    pub fn complete(&self) -> bool {
        self.done
    }
}

/// The scratch name a download is streamed to. A sibling of `dest`, so the rename that follows
/// stays within one filesystem and is therefore atomic.
///
/// **Unique per attempt**, which is not decoration. Two downloads once ran at the same time (the
/// banner and the menu are two entry points to one operation, and nothing stopped the second), and
/// with a shared scratch name they interleaved writes into one file. The first to finish verified
/// it and renamed it into place — while the second, whose file descriptor survives the rename,
/// carried on writing into the *published* file. Bytes landed after verification. It produced a
/// correct file only because both streams happened to carry identical content; a build published
/// mid-download would have corrupted it silently, with the hash check already satisfied.
///
/// Callers should not rely on this alone — [`crate::api::NightdropCore::download_update`] is
/// single-flight — but a name that cannot collide means the worst case is a wasted download rather
/// than a corrupt one.
fn part_path(dest: &std::path::Path, sha256: &str) -> std::path::PathBuf {
    let tag: String = sha256
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .take(16)
        .collect();
    let mut name = dest.file_name().unwrap_or_default().to_os_string();
    name.push(format!(".{tag}.part"));
    dest.with_file_name(name)
}

/// Drop scratch files for any build other than the one being fetched.
///
/// The name carries the expected hash, so a leftover from a superseded release can never be
/// resumed into this one — but it would sit there forever costing tens of megabytes. Only the slot
/// currently in use is spared.
fn sweep_stale_parts(dest: &std::path::Path, keep: &std::path::Path) {
    let Some(dir) = dest.parent() else { return };
    let Some(stem) = dest.file_name().and_then(|n| n.to_str()) else {
        return;
    };
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for e in entries.flatten() {
        let p = e.path();
        if p == keep {
            continue;
        }
        let Some(name) = p.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if name.starts_with(stem) && name.ends_with(".part") {
            crate::diag!("update: discarding a partial download for a superseded build");
            let _ = std::fs::remove_file(&p);
        }
    }
}

/// SHA-256 of a file, read in chunks so a large build is never resident in full.
fn sha256_file(path: &std::path::Path) -> Result<String> {
    use sha2::{Digest, Sha256};
    use std::io::Read as _;

    let mut file = std::fs::File::open(path)?;
    let mut hasher = Sha256::new();
    let mut chunk = vec![0u8; 64 * 1024];
    loop {
        let n = file.read(&mut chunk)?;
        if n == 0 {
            break;
        }
        hasher.update(&chunk[..n]);
    }
    Ok(hasher
        .finalize()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect())
}

/// The ABIs the site currently publishes, sorted so the line is stable between runs. Only ever
/// used for a diagnostic; these are public artifact names, not anything identity-linked.
fn abi_list(manifest: &UpdateManifest) -> String {
    let mut names: Vec<&str> = manifest.android.keys().map(String::as_str).collect();
    names.sort_unstable();
    if names.is_empty() {
        return "none".into();
    }
    names.join(", ")
}

/// Lowercase hex SHA-256.
pub fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut h = Sha256::new();
    h.update(bytes);
    h.finalize().iter().map(|b| format!("{b:02x}")).collect()
}

/// Compare two versions, ignoring build metadata on either side.
pub fn compare(current: &str, latest: &str) -> UpdateStatus {
    UpdateStatus {
        update_available: is_newer(latest, current),
        current: current.to_string(),
        latest: latest.to_string(),
    }
}

/// `MAJOR.MINOR.PATCH` as numbers, ignoring anything from the first `+` or `-`. Missing or
/// unparsable components read as 0, so a malformed version is simply "not newer" rather than an
/// error the user has to see.
fn parts(v: &str) -> (u64, u64, u64) {
    let core = v
        .trim()
        .trim_start_matches('v')
        .split(['+', '-'])
        .next()
        .unwrap_or("");
    let mut it = core
        .split('.')
        .map(|p| p.trim().parse::<u64>().unwrap_or(0));
    (
        it.next().unwrap_or(0),
        it.next().unwrap_or(0),
        it.next().unwrap_or(0),
    )
}

/// Whether `a` is strictly newer than `b`.
fn is_newer(a: &str, b: &str) -> bool {
    parts(a) > parts(b)
}

/// Build the one-line HTTP/1.0 request we send. `HTTP/1.0` with `Connection: close` so the server
/// closes the stream at the end of the body and we need no chunked-encoding handling; no
/// `User-Agent` and no other header, so every install's request is byte-identical.
pub fn request_line(onion: &str, path: &str) -> String {
    format!("GET {path} HTTP/1.0\r\nHost: {onion}\r\nConnection: close\r\n\r\n")
}

/// As [`request_line`] but asking for everything from `from` onwards, to resume a partial download.
///
/// Only ever used for a build, never for the manifest — the manifest request must stay byte
/// identical for every install (see `the_request_is_identical_for_every_install`), and a Range
/// header that varied with local state would make it a beacon.
pub fn range_request_line(onion: &str, path: &str, from: u64) -> String {
    format!(
        "GET {path} HTTP/1.0\r\nHost: {onion}\r\nRange: bytes={from}-\r\nConnection: close\r\n\r\n"
    )
}

/// Split an HTTP/1.0 response into its body, rejecting anything that is not a `200`.
///
/// Deliberately strict and tiny: we control the server and the file, so anything surprising is a
/// reason to give up rather than to interpret.
pub fn body_of(response: &[u8]) -> Result<&[u8]> {
    let head_end = response
        .windows(4)
        .position(|w| w == b"\r\n\r\n")
        .ok_or_else(|| anyhow::anyhow!("update: response had no header terminator"))?;
    let head = std::str::from_utf8(&response[..head_end])
        .map_err(|_| anyhow::anyhow!("update: response headers were not text"))?;
    let status = head.lines().next().unwrap_or_default();
    if !status.starts_with("HTTP/1.0 200") && !status.starts_with("HTTP/1.1 200") {
        anyhow::bail!("update: unexpected status line {status:?}");
    }
    Ok(&response[head_end + 4..])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_newer_release_is_offered_and_the_same_or_older_one_is_not() {
        assert!(compare("0.1.17", "0.1.18").update_available);
        assert!(compare("0.1.17", "0.2.0").update_available);
        assert!(compare("0.9.9", "1.0.0").update_available);
        assert!(!compare("0.1.17", "0.1.17").update_available);
        // A rollback on the site must never nag someone running a newer build.
        assert!(!compare("0.1.17", "0.1.16").update_available);
    }

    #[test]
    fn the_pubspec_build_suffix_is_ignored_on_both_sides() {
        // The app knows itself as "0.1.17+403" (kAppVersion is the whole pubspec string). If the
        // suffix were compared as part of the version, every user would be told to update forever.
        assert!(!compare("0.1.17+403", "0.1.17").update_available);
        assert!(compare("0.1.17+403", "0.1.18").update_available);
        assert!(!compare("0.1.17", "v0.1.17").update_available);
    }

    #[test]
    fn a_malformed_version_is_never_newer() {
        // Garbage on the site must not produce a permanent update nag.
        assert!(!compare("0.1.17", "").update_available);
        assert!(!compare("0.1.17", "not-a-version").update_available);
        assert!(!compare("0.1.17", "latest").update_available);
    }

    #[test]
    fn the_request_is_identical_for_every_install() {
        // No version, no identifier, no User-Agent: the server cannot tell users apart, or tell a
        // first check from a hundredth. If this ever gains a varying field, it becomes a beacon.
        let r = request_line(UPDATE_ONION, MANIFEST_PATH);
        assert_eq!(
            r,
            format!(
                "GET /update.json HTTP/1.0\r\nHost: {UPDATE_ONION}\r\nConnection: close\r\n\r\n"
            )
        );
        assert!(!r.to_ascii_lowercase().contains("user-agent"));
        assert!(!r.contains("0.1."));
    }

    #[test]
    fn only_a_200_yields_a_body() {
        let ok = b"HTTP/1.0 200 OK\r\nContent-Length: 20\r\n\r\n{\"latest\":\"0.1.18\"}";
        assert_eq!(body_of(ok).unwrap(), b"{\"latest\":\"0.1.18\"}");
        for bad in [
            &b"HTTP/1.0 404 Not Found\r\n\r\nnope"[..],
            &b"HTTP/1.0 500 Oops\r\n\r\n"[..],
            &b"garbage with no terminator"[..],
        ] {
            assert!(body_of(bad).is_err(), "should have rejected {bad:?}");
        }
    }

    /// Feed `response` through [`ResponseHead`] in fixed-size pieces, returning the reassembled
    /// body — i.e. exactly what the streaming download would have written to disk.
    fn stream_in_chunks(response: &[u8], chunk: usize) -> Result<Vec<u8>> {
        let mut head = ResponseHead::default();
        let mut body = Vec::new();
        for piece in response.chunks(chunk) {
            body.extend_from_slice(head.push(piece)?);
        }
        assert!(
            head.complete(),
            "head never completed at chunk size {chunk}"
        );
        Ok(body)
    }

    #[test]
    fn a_streamed_response_yields_the_same_body_at_every_chunk_boundary() {
        // The subtle half of streaming. The buffered path could read everything and split once;
        // this one has to find \r\n\r\n across reads, and the interesting case — the terminator
        // straddling two chunks — depends on packet timing that a live Tor circuit will not
        // reproduce on demand. Driving every chunk size covers all four straddle positions.
        let body = b"MZ\x00\x01 a build with \r\n and \r\n\r\n inside it, deliberately";
        let mut response = b"HTTP/1.0 200 OK\r\nContent-Length: 57\r\n\r\n".to_vec();
        response.extend_from_slice(body);

        for size in 1..=response.len() {
            let got = stream_in_chunks(&response, size).unwrap();
            assert_eq!(got, body, "chunk size {size} produced the wrong body");
        }
        // And it agrees with the buffered parser it shares its status check with.
        assert_eq!(body_of(&response).unwrap(), body);
    }

    #[test]
    fn a_streamed_response_reports_the_length_the_server_claimed() {
        // The denominator for progress. Without it a long download can only say "n bytes so far",
        // which does not tell a user or a field log whether it is nearly done or barely started.
        let mut response =
            b"HTTP/1.0 200 OK\r\nContent-Type: application/octet-stream\r\nContent-Length: 12\r\n\r\n"
                .to_vec();
        response.extend_from_slice(b"hello, build");

        // Must hold however the head is split across reads.
        for size in 1..=response.len() {
            let mut head = ResponseHead::default();
            for piece in response.chunks(size) {
                head.push(piece).unwrap();
            }
            assert_eq!(head.content_length(), Some(12), "at chunk size {size}");
        }

        // Case-insensitive, as HTTP requires.
        let lower = b"HTTP/1.0 200 OK\r\ncontent-length: 7\r\n\r\nabcdefg".to_vec();
        let mut head = ResponseHead::default();
        head.push(&lower).unwrap();
        assert_eq!(head.content_length(), Some(7));

        // Absent or junk is not an error — it only costs the denominator.
        for headless in [
            &b"HTTP/1.0 200 OK\r\n\r\nbody"[..],
            &b"HTTP/1.0 200 OK\r\nContent-Length: banana\r\n\r\nbody"[..],
        ] {
            let mut head = ResponseHead::default();
            assert!(head.push(headless).is_ok());
            assert_eq!(head.content_length(), None);
        }
    }

    #[test]
    fn a_streamed_response_rejects_what_the_buffered_one_rejects() {
        // A non-200 must fail before a single byte reaches the file, or a 404 page gets written
        // where a build should be and only the hash catches it.
        for bad in [
            &b"HTTP/1.0 404 Not Found\r\n\r\nnope"[..],
            &b"HTTP/1.0 500 Oops\r\n\r\n"[..],
        ] {
            for size in 1..=bad.len() {
                assert!(
                    stream_in_chunks(bad, size).is_err(),
                    "accepted {bad:?} at chunk size {size}"
                );
            }
        }
        // A head that never terminates must be bounded rather than buffered forever.
        let endless = vec![b'x'; MAX_MANIFEST_BYTES + 1024];
        let mut head = ResponseHead::default();
        let mut err = None;
        for piece in endless.chunks(1024) {
            if let Err(e) = head.push(piece) {
                err = Some(e);
                break;
            }
        }
        assert!(err.is_some(), "an unterminated head must be rejected");
        assert!(!head.complete());
    }

    /// How many scratch files are lying around. Counted rather than probed by name, because the
    /// name is deliberately unique per attempt — and "no .part survives" is the property that
    /// actually matters, for any name.
    fn leftover_parts(dir: &std::path::Path) -> usize {
        std::fs::read_dir(dir)
            .map(|entries| {
                entries
                    .flatten()
                    .filter(|e| e.file_name().to_string_lossy().ends_with(".part"))
                    .count()
            })
            .unwrap_or(0)
    }

    fn manifest_with(sha: &str) -> UpdateManifest {
        serde_json::from_str(&format!(
            r#"{{"latest":"0.1.18","android":{{"arm64-v8a":{{"url":"/applications/android/NightDrop-arm64-v8a.apk","sha256":"{sha}"}}}}}}"#
        ))
        .unwrap()
    }

    #[test]
    fn a_manifest_without_downloads_still_reports_the_version() {
        // The site may publish a version before the APKs are in place. That must still tell the
        // user something; it just cannot offer a download.
        let m: UpdateManifest = serde_json::from_str(r#"{"latest":"0.1.18"}"#).unwrap();
        assert_eq!(m.latest, "0.1.18");
        assert!(m.android.is_empty());
    }

    #[test]
    fn the_build_offered_is_this_devices_abi_and_never_the_universal_one() {
        // Not cosmetic, and not a size optimisation. --split-per-abi numbers the per-ABI APKs
        // base*10+abi (4031/4032/4033) and leaves the universal APK on the bare base (403), so
        // offering "universal" to anyone running a per-ABI install is a downgrade by versionCode
        // and Android refuses it. F-Droid ships per-ABI, so that is most users — they would wait
        // out ~119MB over Tor and then be told "App not installed".
        assert_ne!(native_abi(), "universal");
        // The names are MediaStore-free platform constants; they have to match what
        // scripts/gen-update-manifest.sh publishes as keys, or nothing is ever found.
        for (arch, abi) in [
            ("aarch64", "arm64-v8a"),
            ("arm", "armeabi-v7a"),
            ("x86_64", "x86_64"),
        ] {
            if std::env::consts::ARCH == arch {
                assert_eq!(native_abi(), abi);
            }
        }
    }

    #[test]
    fn a_build_whose_hash_does_not_match_is_never_written() {
        // The whole point of the hash. If a mismatched download reached the destination path, the
        // user could be one tap from installing it — so the file must not exist at all.
        let dir = std::env::temp_dir().join(format!("nd-update-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let dest = dir.join("bad.apk");
        let _ = std::fs::remove_file(&dest);

        struct Server(Vec<u8>);
        impl Transport for Server {
            fn address(&self) -> crate::transport::Address {
                "srv".into()
            }
            fn send(&self, _p: &str, _f: &[u8]) -> Result<()> {
                Ok(())
            }
            fn try_recv(&self) -> Option<(crate::transport::Address, Vec<u8>)> {
                None
            }
            // Streams like the real one: writes the bytes to the path it is given, which is the
            // scratch file, and never to `dest`.
            fn onion_get_to_file(
                &self,
                req: crate::transport::FileFetch<'_>,
                progress: &dyn Fn(u64, Option<u64>),
            ) -> Option<Result<u64>> {
                let dest = req.dest;
                progress(self.0.len() as u64, Some(self.0.len() as u64));
                Some(
                    std::fs::write(dest, &self.0)
                        .map(|()| self.0.len() as u64)
                        .map_err(Into::into),
                )
            }
        }

        let served = b"not the build you were promised".to_vec();
        let wrong = manifest_with(&"0".repeat(64));
        let err = download(
            &Server(served.clone()),
            &wrong,
            "arm64-v8a",
            &dest,
            &|_, _| {},
        )
        .unwrap_err();
        assert!(err.to_string().contains("did not match"), "{err}");
        assert!(
            !dest.exists(),
            "a mismatched download must not be left on disk"
        );
        // And the scratch file goes too. It holds a full-size build that failed verification;
        // leaving it behind would quietly cost the user tens of megabytes per failed attempt.
        assert_eq!(
            leftover_parts(&dir),
            0,
            "a rejected download must not be left as a .part either"
        );

        // The same bytes with the right hash do land.
        let right = manifest_with(&sha256_hex(&served));
        let n = download(
            &Server(served.clone()),
            &right,
            "arm64-v8a",
            &dest,
            &|_, _| {},
        )
        .unwrap();
        assert_eq!(n as usize, served.len());
        assert_eq!(std::fs::read(&dest).unwrap(), served);
        assert_eq!(
            leftover_parts(&dir),
            0,
            "the scratch file must be renamed, not copied and left"
        );

        // An ABI we publish nothing for is an error, not a silent empty file.
        assert!(download(&Server(served), &right, "riscv64", &dest, &|_, _| {}).is_err());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn an_in_flight_download_is_never_visible_at_the_destination() {
        // The reason streaming needed a scratch path at all. While the bytes are arriving they are
        // unverified, and `dest` is the path the app will publish to Downloads — so at no point
        // during the transfer may a file exist there. The transport below asserts that from
        // *inside* the download, which is the only moment it can be observed.
        let dir = std::env::temp_dir().join(format!("nd-update-inflight-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let dest = dir.join("build.apk");
        let _ = std::fs::remove_file(&dest);

        struct Watcher {
            body: Vec<u8>,
            dest: std::path::PathBuf,
        }
        impl Transport for Watcher {
            fn address(&self) -> crate::transport::Address {
                "srv".into()
            }
            fn send(&self, _p: &str, _f: &[u8]) -> Result<()> {
                Ok(())
            }
            fn try_recv(&self) -> Option<(crate::transport::Address, Vec<u8>)> {
                None
            }
            fn onion_get_to_file(
                &self,
                req: crate::transport::FileFetch<'_>,
                _progress: &dyn Fn(u64, Option<u64>),
            ) -> Option<Result<u64>> {
                let target = req.dest;
                assert_ne!(target, self.dest, "a download must not stream to dest");
                assert!(
                    target.to_string_lossy().ends_with(".part"),
                    "expected a .part scratch file, got {}",
                    target.display()
                );
                // Write half, check, write the rest — mid-transfer is exactly when a crash or a
                // curious file manager would see the destination.
                let half = self.body.len() / 2;
                std::fs::write(target, &self.body[..half]).unwrap();
                assert!(
                    !self.dest.exists(),
                    "the destination existed while bytes were still arriving"
                );
                std::fs::write(target, &self.body).unwrap();
                Some(Ok(self.body.len() as u64))
            }
        }

        let body = b"a build long enough to be written in two goes".to_vec();
        let m = manifest_with(&sha256_hex(&body));
        let t = Watcher {
            body: body.clone(),
            dest: dest.clone(),
        };
        assert_eq!(
            download(&t, &m, "arm64-v8a", &dest, &|_, _| {}).unwrap(),
            body.len() as u64
        );
        assert_eq!(std::fs::read(&dest).unwrap(), body);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn an_interrupted_download_resumes_instead_of_starting_over() {
        // Over Tor a failed transfer is minutes thrown away, and the partial is sitting right
        // there. The scratch file is keyed by the expected hash, so a partial from a superseded
        // build can never be resumed into this one, and the final SHA-256 over the assembled file
        // is what decides acceptability — which is why no expiry is needed on a .part.
        let dir = std::env::temp_dir().join(format!("nd-update-resume-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let dest = dir.join("build.apk");

        let body: Vec<u8> = (0u8..=255).cycle().take(5000).collect();

        /// Serves `cut` bytes and then fails; on a later call, honours the offset it is given.
        struct Flaky {
            body: Vec<u8>,
            cut: usize,
            seen: std::sync::Mutex<Vec<u64>>,
        }
        impl Transport for Flaky {
            fn address(&self) -> crate::transport::Address {
                "srv".into()
            }
            fn send(&self, _p: &str, _f: &[u8]) -> Result<()> {
                Ok(())
            }
            fn try_recv(&self) -> Option<(crate::transport::Address, Vec<u8>)> {
                None
            }
            fn onion_get_to_file(
                &self,
                req: crate::transport::FileFetch<'_>,
                _progress: &dyn Fn(u64, Option<u64>),
            ) -> Option<Result<u64>> {
                let (dest, resume_from) = (req.dest, req.resume_from);
                self.seen.lock().unwrap().push(resume_from);
                use std::io::Write as _;
                if resume_from == 0 {
                    // First attempt: write a prefix, then die.
                    std::fs::write(dest, &self.body[..self.cut]).unwrap();
                    return Some(Err(anyhow::anyhow!("connection died")));
                }
                // Resume: append exactly what is missing, as a 206 would.
                let mut f = std::fs::OpenOptions::new().append(true).open(dest).unwrap();
                f.write_all(&self.body[resume_from as usize..]).unwrap();
                Some(Ok(self.body.len() as u64))
            }
        }

        let t = Flaky {
            body: body.clone(),
            cut: 1500,
            seen: std::sync::Mutex::new(Vec::new()),
        };
        let m = manifest_with(&sha256_hex(&body));

        // First attempt fails, and must LEAVE the partial behind — that is the whole point.
        assert!(download(&t, &m, "arm64-v8a", &dest, &|_, _| {}).is_err());
        assert_eq!(leftover_parts(&dir), 1, "the partial is the resume state");
        assert!(!dest.exists(), "nothing lands at dest on a failure");

        // Second attempt resumes from exactly what was kept, and completes.
        let n = download(&t, &m, "arm64-v8a", &dest, &|_, _| {}).unwrap();
        assert_eq!(n as usize, body.len());
        assert_eq!(
            std::fs::read(&dest).unwrap(),
            body,
            "the halves must join cleanly"
        );
        assert_eq!(
            leftover_parts(&dir),
            0,
            "a completed download leaves no scratch file"
        );
        assert_eq!(
            *t.seen.lock().unwrap(),
            vec![0, 1500],
            "the second attempt must ask for the bytes it does not have, not start over"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_partial_for_a_superseded_build_is_never_resumed_into_this_one() {
        // The scratch name carries the expected hash. A leftover from an older release therefore
        // cannot be appended to — it would produce a file that fails its hash after a full
        // download, wasting the transfer it was supposed to save.
        let dir = std::env::temp_dir().join(format!("nd-update-stale-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let dest = dir.join("build.apk");

        let old_slot = part_path(&dest, &"a".repeat(64));
        std::fs::write(&old_slot, b"bytes from a build we no longer want").unwrap();

        let body = b"the build we actually asked for".to_vec();
        let m = manifest_with(&sha256_hex(&body));
        let new_slot = part_path(&dest, &sha256_hex(&body));
        assert_ne!(old_slot, new_slot, "different builds must not share a slot");

        struct Server(Vec<u8>);
        impl Transport for Server {
            fn address(&self) -> crate::transport::Address {
                "srv".into()
            }
            fn send(&self, _p: &str, _f: &[u8]) -> Result<()> {
                Ok(())
            }
            fn try_recv(&self) -> Option<(crate::transport::Address, Vec<u8>)> {
                None
            }
            fn onion_get_to_file(
                &self,
                req: crate::transport::FileFetch<'_>,
                _progress: &dyn Fn(u64, Option<u64>),
            ) -> Option<Result<u64>> {
                let (dest, resume_from) = (req.dest, req.resume_from);
                assert_eq!(resume_from, 0, "a stale partial must not be resumed from");
                std::fs::write(dest, &self.0).unwrap();
                Some(Ok(self.0.len() as u64))
            }
        }

        download(&Server(body.clone()), &m, "arm64-v8a", &dest, &|_, _| {}).unwrap();
        assert_eq!(std::fs::read(&dest).unwrap(), body);
        assert!(
            !old_slot.exists(),
            "the superseded partial must be swept, not left to rot"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_transport_without_an_anonymized_path_makes_no_check_at_all() {
        // The whole point: no transport falls back to clearnet to satisfy the update check. The
        // default `onion_get` is None, so this must be Ok(None) — not an error the UI shows, and
        // certainly not a direct fetch.
        let memory = crate::transport::MemoryNetwork::default().endpoint("me");
        assert_eq!(check(&memory, "0.1.17").unwrap(), None);
        let closed = crate::transport::ClosedTransport::new("me".into());
        assert_eq!(check(&closed, "0.1.17").unwrap(), None);
    }
}
