//! Update check (`ARCHITECTURE.md` §6): ask **our own onion site** whether a newer release
//! exists, over Tor, and tell the user. Nothing here downloads or installs anything.
//!
//! ## Why this exists
//!
//! The Android build comes from F-Droid and updates itself. The **AppImage does not** — it is a
//! file on disk, and a user who downloaded one in 2026-08 is still running it today unless they
//! went looking. That is how a stale download link left people on 0.1.15 without the onion-identity
//! fix for three days (`docs/advisories/2026-08-05-linux-download-pinned-to-0.1.15.md`). A user who
//! cannot tell they are running a superseded build cannot act on a security fix.
//!
//! ## What it must not become
//!
//! An update check is a beacon, and this is a privacy tool, so the shape is deliberately the
//! smallest one that works:
//!
//! * **Over Tor, to an onion, always.** [`Transport::onion_get`] has no clearnet path; a transport
//!   that cannot fetch anonymously returns `None` and we skip the check entirely rather than
//!   reaching for anything else (§6, and the ClosedTransport DNS leak that taught us to say so).
//! * **The request carries nothing.** A plain `GET` of one static file, no version, no identifier,
//!   no cookie, no varying header. The server cannot distinguish one user from another, or a
//!   first check from a hundredth — it sees an anonymous request for a public file, which is what
//!   any visitor to the site makes. The comparison happens **here**, on the device.
//! * **It answers a question, it does not act.** We return a struct; the UI shows a notice; the
//!   user chooses. Nothing is fetched, written, or executed as a result.
//! * **Failure is silence.** The site being down, Tor being slow, or the JSON being malformed are
//!   all "no answer", never a warning. A user must not learn to dismiss update warnings.
//!
//! The onion address self-authenticates — a v3 `.onion` *is* an ed25519 public key, so reaching
//! it proves we reached the site and not an impostor, with no certificate authority involved.

use serde::Deserialize;

use crate::transport::Transport;
use crate::Result;

/// Our onion site, which serves [`MANIFEST_PATH`]. Baked in rather than configurable: an
/// attacker who could point the update check somewhere else could tell a user they are up to
/// date forever.
///
/// **This address is permanent.** It ships inside released binaries, so it cannot be changed for
/// anyone already running one — losing the service key would strand every install's update check
/// with no way to fix it from our side. Back the key up like the relay's (`RELAYS.md`).
pub const UPDATE_ONION: &str = "z6xw2ywlybjeskki4jons5ujepc2pedp5qkgvtbyxorie46qnjpnzqqd.onion";

/// The virtual port the onion site serves HTTP on.
pub const UPDATE_PORT: u16 = 80;

/// The static file holding the current release. Generated by `make config` from
/// `app/pubspec.yaml`, so the published version cannot drift from the released one.
pub const MANIFEST_PATH: &str = "/update.json";

/// Hard cap on the manifest. It is a handful of bytes of JSON; anything larger is not ours, and
/// an unbounded read from a remote host is how a small feature becomes an OOM.
pub const MAX_MANIFEST_BYTES: usize = 8 * 1024;

/// What the onion site publishes.
#[derive(Debug, Deserialize)]
pub struct UpdateManifest {
    /// The current release, as a bare `MAJOR.MINOR.PATCH` string.
    pub latest: String,
}

/// The answer for the UI.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UpdateStatus {
    /// What this build is.
    pub current: String,
    /// What the site says is current.
    pub latest: String,
    /// Whether `latest` is strictly newer than `current`.
    pub update_available: bool,
}

/// Ask the onion site what the current release is and compare it with `current_version`.
///
/// `current_version` accepts the pubspec form (`"0.1.17+403"`); the build metadata is ignored.
/// Returns `Ok(None)` when the transport cannot fetch anonymously — the caller does nothing.
pub fn check(transport: &dyn Transport, current_version: &str) -> Result<Option<UpdateStatus>> {
    let Some(fetched) = transport.onion_get(UPDATE_ONION, UPDATE_PORT, MANIFEST_PATH) else {
        // Not an error: this transport has no anonymized path, so there is no check to make.
        return Ok(None);
    };
    let manifest: UpdateManifest = serde_json::from_slice(&fetched?)?;
    Ok(Some(compare(current_version, &manifest.latest)))
}

/// Compare two versions, ignoring build metadata on either side.
pub fn compare(current: &str, latest: &str) -> UpdateStatus {
    UpdateStatus {
        update_available: is_newer(latest, current),
        current: current.to_string(),
        latest: latest.to_string(),
    }
}

/// `MAJOR.MINOR.PATCH` as numbers, ignoring anything from the first `+` or `-`. Missing or
/// unparsable components read as 0, so a malformed version is simply "not newer" rather than an
/// error the user has to see.
fn parts(v: &str) -> (u64, u64, u64) {
    let core = v
        .trim()
        .trim_start_matches('v')
        .split(['+', '-'])
        .next()
        .unwrap_or("");
    let mut it = core
        .split('.')
        .map(|p| p.trim().parse::<u64>().unwrap_or(0));
    (
        it.next().unwrap_or(0),
        it.next().unwrap_or(0),
        it.next().unwrap_or(0),
    )
}

/// Whether `a` is strictly newer than `b`.
fn is_newer(a: &str, b: &str) -> bool {
    parts(a) > parts(b)
}

/// Build the one-line HTTP/1.0 request we send. `HTTP/1.0` with `Connection: close` so the server
/// closes the stream at the end of the body and we need no chunked-encoding handling; no
/// `User-Agent` and no other header, so every install's request is byte-identical.
pub fn request_line(onion: &str, path: &str) -> String {
    format!("GET {path} HTTP/1.0\r\nHost: {onion}\r\nConnection: close\r\n\r\n")
}

/// Split an HTTP/1.0 response into its body, rejecting anything that is not a `200`.
///
/// Deliberately strict and tiny: we control the server and the file, so anything surprising is a
/// reason to give up rather than to interpret.
pub fn body_of(response: &[u8]) -> Result<&[u8]> {
    let head_end = response
        .windows(4)
        .position(|w| w == b"\r\n\r\n")
        .ok_or_else(|| anyhow::anyhow!("update: response had no header terminator"))?;
    let head = std::str::from_utf8(&response[..head_end])
        .map_err(|_| anyhow::anyhow!("update: response headers were not text"))?;
    let status = head.lines().next().unwrap_or_default();
    if !status.starts_with("HTTP/1.0 200") && !status.starts_with("HTTP/1.1 200") {
        anyhow::bail!("update: unexpected status line {status:?}");
    }
    Ok(&response[head_end + 4..])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_newer_release_is_offered_and_the_same_or_older_one_is_not() {
        assert!(compare("0.1.17", "0.1.18").update_available);
        assert!(compare("0.1.17", "0.2.0").update_available);
        assert!(compare("0.9.9", "1.0.0").update_available);
        assert!(!compare("0.1.17", "0.1.17").update_available);
        // A rollback on the site must never nag someone running a newer build.
        assert!(!compare("0.1.17", "0.1.16").update_available);
    }

    #[test]
    fn the_pubspec_build_suffix_is_ignored_on_both_sides() {
        // The app knows itself as "0.1.17+403" (kAppVersion is the whole pubspec string). If the
        // suffix were compared as part of the version, every user would be told to update forever.
        assert!(!compare("0.1.17+403", "0.1.17").update_available);
        assert!(compare("0.1.17+403", "0.1.18").update_available);
        assert!(!compare("0.1.17", "v0.1.17").update_available);
    }

    #[test]
    fn a_malformed_version_is_never_newer() {
        // Garbage on the site must not produce a permanent update nag.
        assert!(!compare("0.1.17", "").update_available);
        assert!(!compare("0.1.17", "not-a-version").update_available);
        assert!(!compare("0.1.17", "latest").update_available);
    }

    #[test]
    fn the_request_is_identical_for_every_install() {
        // No version, no identifier, no User-Agent: the server cannot tell users apart, or tell a
        // first check from a hundredth. If this ever gains a varying field, it becomes a beacon.
        let r = request_line(UPDATE_ONION, MANIFEST_PATH);
        assert_eq!(
            r,
            format!(
                "GET /update.json HTTP/1.0\r\nHost: {UPDATE_ONION}\r\nConnection: close\r\n\r\n"
            )
        );
        assert!(!r.to_ascii_lowercase().contains("user-agent"));
        assert!(!r.contains("0.1."));
    }

    #[test]
    fn only_a_200_yields_a_body() {
        let ok = b"HTTP/1.0 200 OK\r\nContent-Length: 20\r\n\r\n{\"latest\":\"0.1.18\"}";
        assert_eq!(body_of(ok).unwrap(), b"{\"latest\":\"0.1.18\"}");
        for bad in [
            &b"HTTP/1.0 404 Not Found\r\n\r\nnope"[..],
            &b"HTTP/1.0 500 Oops\r\n\r\n"[..],
            &b"garbage with no terminator"[..],
        ] {
            assert!(body_of(bad).is_err(), "should have rejected {bad:?}");
        }
    }

    #[test]
    fn a_transport_without_an_anonymized_path_makes_no_check_at_all() {
        // The whole point: no transport falls back to clearnet to satisfy the update check. The
        // default `onion_get` is None, so this must be Ok(None) — not an error the UI shows, and
        // certainly not a direct fetch.
        let memory = crate::transport::MemoryNetwork::default().endpoint("me");
        assert_eq!(check(&memory, "0.1.17").unwrap(), None);
        let closed = crate::transport::ClosedTransport::new("me".into());
        assert_eq!(check(&closed, "0.1.17").unwrap(), None);
    }
}
