// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_tick`, `decode_store_key`, `drive`, `emit_chats`, `emit`, `lock`, `maybe_flush`, `media`, `new`, `next_cover_delay`, `now_secs`, `parse_invite`, `random_secret_words`, `random_short_code`, `random_slot`, `save_soon`, `save`, `spawn_poller`, `system_tagged`, `system`, `text`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Inner`, `Persist`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `drop`, `drop`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `address`, `new_with_transport`, `poll_once`

/// Subscribe to push events from the core (flutter_rust_bridge stream). Call once at
/// startup; the UI refreshes its view whenever an event arrives.
Stream<AppEvent> subscribe() => RustLib.instance.api.crateApiSubscribe();

/// Drop the event sink (closes the stream). Call on app/teardown so no port lingers.
Future<void> unsubscribe() => RustLib.instance.api.crateApiUnsubscribe();

/// Turn on opt-in operational diagnostics (`crate::diag`) — off unless a debugging build asks
/// for it. These lines record protocol outcomes (which leg ran, how many relays answered), never
/// identity keys, onion addresses, invite codes, or names; the identity-linked `devlog!` lines
/// stay compiled out of release builds either way.
Future<void> setDiagnostics({required bool enabled}) =>
    RustLib.instance.api.crateApiSetDiagnostics(enabled: enabled);

/// Delete arti's entry-guard + circuit-timing state under `state_dir` — but NOT the onion keystore,
/// so the device keeps its stable `.onion`. The next Tor bootstrap then picks fresh entry guards.
/// This is the recovery for a **wedged guard set** (guards that have churned out of the network):
/// a client stuck on them can neither publish its own onion nor reach the relay, and a plain
/// re-bootstrap reuses the same guards, so it can't recover on its own (§6). Call this with the
/// core shut down, then build a fresh core. No-op if the files are absent.
Future<void> resetTorGuards({required String stateDir}) =>
    RustLib.instance.api.crateApiResetTorGuards(stateDir: stateDir);

/// A fresh random 32-byte at-rest key (base64) for the persisted state file. Generated once
/// per device, stored in the OS secure store on the Dart side, and passed back to
/// [`new_tor`](NightdropCore::new_tor) on later launches to restore the saved state.
Future<String> randomStoreKey() =>
    RustLib.instance.api.crateApiRandomStoreKey();

/// Whether this store's key is protected by a passphrase rather than sitting in the platform
/// keystore. `dir` is the same directory the state blob lives in.
Future<bool> storeIsLocked({required String dir}) =>
    RustLib.instance.api.crateApiStoreIsLocked(dir: dir);

/// Put the store key behind `passphrase`. The caller **must** then delete its keystore copy of
/// `key_b64`; leaving it there defeats the entire purpose, since the key would still be readable
/// without the passphrase.
///
/// A short PIN cannot be made safe here: an attacker holding the lock file tries every 4-6 digit
/// value offline regardless of the derivation cost. Only a passphrase with real entropy protects
/// an imaged device, and the UI must say so rather than implying otherwise.
Future<void> setStorePassphrase(
        {required String dir,
        required String keyB64,
        required String passphrase}) =>
    RustLib.instance.api.crateApiSetStorePassphrase(
        dir: dir, keyB64: keyB64, passphrase: passphrase);

/// Recover the store key from `secret`, base64-encoded for the Dart side to hand straight back to a
/// core constructor. Errors on a wrong secret without saying which part was wrong.
///
/// A **duress** secret (#3) returns `duress: true` instead of a key; the caller must then wipe (see
/// `docs/design/duress-wipe.md`). Both slots are always derived, so the two outcomes are
/// indistinguishable by timing to anyone watching the user unlock.
Future<StoreUnlock> unlockStoreKey(
        {required String dir, required String secret}) =>
    RustLib.instance.api.crateApiUnlockStoreKey(dir: dir, secret: secret);

/// Arm (or replace) the **duress** secret (#3) — the second secret that wipes instead of opening.
/// Requires the normal secret, so an adversary who coerced one unlock cannot re-arm or disarm it.
///
/// The lock file is written so that an armed duress slot is **indistinguishable** from an unarmed
/// one, and the UI must never display which it is: showing it would mean persisting it, which is
/// the tell the design removes. Warn the user at this moment and nowhere else.
Future<void> setDuressSecret(
        {required String dir,
        required String passphrase,
        required String duress}) =>
    RustLib.instance.api.crateApiSetDuressSecret(
        dir: dir, passphrase: passphrase, duress: duress);

/// Disarm duress. Requires the normal secret. Succeeds whether or not anything was armed, so a
/// caller who has not proven they know the state cannot infer it from the outcome.
Future<void> clearDuressSecret(
        {required String dir, required String passphrase}) =>
    RustLib.instance.api
        .crateApiClearDuressSecret(dir: dir, passphrase: passphrase);

/// Turn **cover traffic** (#4) on or off. Off by default, and deliberately opt-in: it costs the
/// user battery and bandwidth continuously, and costs whoever runs the relay — usually a
/// volunteer — the load of carrying dummy mail.
///
/// What it buys: the relay's per-mailbox timing profile stops being a clean read of when you are
/// active. What it does **not** buy, and the UI must say so: this is chaff, not constant-rate
/// transmission. Real messages still post *in addition* to the cover, so a patient observer can
/// still see aggregate volume rise when you are genuinely busy. It raises the cost of traffic
/// analysis; it does not end it. See `docs/design/cover-traffic.md` §4.
Future<void> setCoverTraffic({required bool enabled}) =>
    RustLib.instance.api.crateApiSetCoverTraffic(enabled: enabled);

/// Whether cover traffic is currently on.
Future<bool> coverTrafficEnabled() =>
    RustLib.instance.api.crateApiCoverTrafficEnabled();

/// Whether a wipe code is armed. Needs the **store key**, which is precisely what makes this safe
/// to expose: the unlocked app can tell the user where they stand, while someone holding only an
/// image of the device still cannot — reading it requires the key the lock protects.
///
/// Offering no readout at all was worse. A user who cannot see whether their wipe code is armed can
/// believe they have one when they don't, and find out while being coerced.
Future<bool> duressIsArmed({required String dir, required String keyB64}) =>
    RustLib.instance.api.crateApiDuressIsArmed(dir: dir, keyB64: keyB64);

/// Whether `secret` is the **normal** secret — so a settings flow can reject a wrong one up front
/// rather than after the user has filled in everything that follows. A duress secret answers
/// `false` and wipes nothing: its contract is the lock screen.
Future<bool> storeSecretIsCorrect(
        {required String dir, required String secret}) =>
    RustLib.instance.api.crateApiStoreSecretIsCorrect(dir: dir, secret: secret);

/// Delete the lock file without any secret — **only** for the duress wipe, where the store it
/// protects is destroyed in the same breath. Leaving it behind would show a lock screen for a store
/// that no longer exists.
Future<void> destroyStoreLock({required String dir}) =>
    RustLib.instance.api.crateApiDestroyStoreLock(dir: dir);

/// Drop the passphrase lock, returning the store key so the caller can restore its keystore copy.
/// Without that the store would be unopenable — the lock file was the only way in.
Future<String> clearStorePassphrase(
        {required String dir, required String passphrase}) =>
    RustLib.instance.api
        .crateApiClearStorePassphrase(dir: dir, passphrase: passphrase);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NightdropCore>>
abstract class NightdropCore implements RustOpaqueInterface {
  /// Approve or decline a pending inbound request. On approval it becomes a contact.
  Future<void> authorize({required String contactId, required bool accept});

  /// Return the prepared backup blob (already password-encrypted) so the UI can hand it to
  /// the OS file picker — needed on Android, where the app can only write to a user-chosen
  /// location (Documents/Downloads) via the Storage Access Framework, not a private path.
  /// Leaves the pending blob in place so a cancelled save can be retried.
  Future<Uint8List> backupBytes();

  /// Join from a scanned QR payload (pre-authorized, §5a):
  /// `nightdrop://pair?addr=...&ik=...&otk=...`. Opens a session and sends the Hello. This
  /// is the relay-free pairing path used over Tor (the QR carries the inviter's `.onion`).
  Future<Contact> connectViaQr({required String payload});

  /// All current contacts.
  Future<List<Contact>> contacts();

  /// Begin an encrypted backup: build the blob, hold it pending, and return the
  /// **recovery password to show once** (§7). Randomly generated, never persisted; losing
  /// it loses the backup. `full` picks the content matrix (#7): `true` = Full (history +
  /// media included), `false` = Lite (identity + onion + contacts + sessions only). The UI
  /// shows the password for acknowledgment, then calls [`save_backup`](Self::save_backup).
  Future<String> createBackup({required bool full});

  /// Begin a **single-chat scoped backup** (#8): prepare a blob carrying only `contact_id`'s
  /// chat (history + media if `full`) and return the one-time recovery password. Held pending
  /// exactly like [`create_backup`](Self::create_backup) — acknowledge the password, then
  /// [`save_backup`](Self::save_backup) / [`backup_bytes`](Self::backup_bytes) to write it.
  Future<String> createChatBackup(
      {required String contactId, required bool full});

  /// Create a pairing invite: a `slot-secret-words` short code plus a QR payload that
  /// embeds our address and a real pre-key bundle (§5a). In demo mode it also simulates
  /// a peer joining, producing a request to approve.
  Future<PairingInvite> createInvite();

  /// Generate this device's **access key** for a PRIVATE relay (restricted discovery, §3.2).
  /// Returns the public `descriptor:x25519:…` string to give the relay operator, who runs
  /// `nightdrop-relay authorize-client <name> <key>`. arti stores the private half and presents it
  /// automatically whenever this device dials that relay, so after authorization the private relay
  /// becomes reachable. Only meaningful on the Tor transport; errors otherwise. Generating a key
  /// for a public relay is harmless but unnecessary.
  Future<String> createRelayAccessKey({required String relayOnion});

  /// Enable an **opt-in server backup** (§7c invariant): post an opaque, password-encrypted
  /// backup blob to the relay for `ttl_hours` (clamped to 1..=36; default 24). The recovery
  /// `password` is randomly generated here, returned to be shown **once**, and never
  /// persisted — the relay never sees it. The returned exact expiry drives the acknowledgment
  /// screen the invariant requires. Losing the password loses the backup, by design.
  Future<ServerBackupInfo> createServerBackup(
      {required BigInt ttlHours, required bool full});

  /// Create a short-code invite via the rendezvous mailbox (§5b/§5c). Returns the full
  /// `slot-secret-words` code to read out; the secret never reaches the relay. Returns
  /// immediately — the background poller completes the interactive SPAKE2 handshake with a
  /// joiner (`Node::service_pending_invites`), so this device must stay reachable meanwhile.
  Future<String> createShortCodeInvite();

  static Future<NightdropCore> default_() =>
      RustLib.instance.api.crateApiNightdropCoreDefault();

  /// Delete a chat (TODO #1): signal the peer (who then sees a "chat deleted" notice) and
  /// remove it locally. Creating a new chat is required to talk again.
  Future<void> deleteChat({required String contactId});

  /// [`logout`](Self::logout) for the **duress wipe** (#3): same teardown, but *every* live chat
  /// is told, not just un-backed ones, since no restore is coming. The notice is the ordinary
  /// "chat deleted" — never anything that identifies this as a duress event.
  ///
  /// Best-effort by design. The caller must wipe regardless of the count returned: a wipe that
  /// can be prevented by taking the phone off the network is not a wipe.
  Future<int> duressLogout();

  /// Edit the text of one of our own messages (`msg_id` from [`ChatMessage`]). Allowed
  /// within 15 minutes of sending, or at any time while the message is still queued on
  /// the relay (the peer never saw it — the queued blob is recalled and replaced).
  /// The message is marked `edited`; the peer's copy updates via an E2E edit frame.
  Future<void> editMessage(
      {required String contactId, required String msgId, required String text});

  /// This device's public identity handle.
  Future<Identity> identity();

  /// Contacts whose inbound chat request awaits the user's approval (§5).
  Future<List<Contact>> incomingRequests();

  /// Join a chat from a `slot-secret-words` short code (§5b): run the interactive SPAKE2
  /// handshake through the rendezvous, then open a session toward the inviter. The handshake
  /// blocks on relay round-trips, so it runs **without** the core lock held; only the brief
  /// identity-mutating steps (relay lookup, session open) take the lock.
  Future<Contact> joinViaShortCode({required String code});

  /// Peer-facing logout (#7 / §11.6): tell the peer of every **un-backed** chat that it's
  /// closed (so their mail isn't lost to a since-deleted identity), leave backed-up chats
  /// silent (their mail queues until we restore within 24h), and clear all chats. The app
  /// then wipes the local state file + secure key. Call **before** deleting local files.
  ///
  /// Returns the number of un-backed chats whose "chat deleted" notice we could **not** get out
  /// (neither queued on a relay nor sent directly), so the UI can warn "some contacts may not
  /// have been notified" (§1.3). `0` means every notice was queued/sent.
  Future<int> logout();

  /// Decrypt and return an attachment's bytes (for inline image display).
  Future<Uint8List> mediaBytes({required String mediaId});

  /// Decrypt an attachment to a temp file and return its path (to open a video/file in the
  /// system player without copying the bytes back through the bridge).
  Future<String> mediaToFile({required String mediaId, required String ext});

  /// Merge a scoped backup file at `path` into the **current** identity (#8): add the chat(s)
  /// it carries without disturbing our identity or any active session (existing chats only
  /// gain missing history). Returns how many messages were merged.
  Future<int> mergeBackup({required String path, required String password});

  /// Messages for a contact, oldest first.
  Future<List<ChatMessage>> messages({required String contactId});

  /// Our advertised **extra** relay addresses (#17) — relays that also host our mailbox, on top
  /// of the built-in default. Empty by default.
  Future<List<String>> myRelays();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Demo core: a fresh identity on an in-memory network with auto-replying peers and
  /// **no** background poller (so messaging is synchronous and flutter_rust_bridge
  /// stream tests don't see continuous events). This is what the app uses today.
  static Future<NightdropCore> newInstance() =>
      RustLib.instance.api.crateApiNightdropCoreNew();

  /// Real core over the **local-network (LAN / Wi-Fi) transport** — a Briar-style offline path
  /// for when there is no internet, or Tor is blocked, but paired devices share a network (§6).
  /// Binds a listener on `port` (`0` = an ephemeral port) across all interfaces and advertises
  /// this machine's detected LAN IP, so a peer on the same network reaches us with no public
  /// address or port-forwarding. The canonical flow is QR pairing in the same room; frames then
  /// flow directly, end-to-end encrypted and fixed-size padded, over the LAN.
  ///
  /// `relay_addr` is optional (offline LANs usually have none). Persistence (`persist_path` +
  /// base64 `persist_key`) behaves exactly as in [`new_tor`](Self::new_tor): restore if the file
  /// exists, else create + save a fresh identity. Because a LAN address changes between runs, on
  /// restore we announce the new address to contacts in-band (§5c) so they can still reach us —
  /// pass a **fixed** `port` for a more stable address.
  ///
  /// Anonymity note: LAN traffic is **not** anonymized (a local observer sees two IPs talking);
  /// only the content is encrypted. This is a censorship/blackout fallback, not a Tor replacement.
  static Future<NightdropCore> newLan(
          {required int port,
          String? relayAddr,
          String? persistPath,
          String? persistKey}) =>
      RustLib.instance.api.crateApiNightdropCoreNewLan(
          port: port,
          relayAddr: relayAddr,
          persistPath: persistPath,
          persistKey: persistKey);

  /// Real networked core over plain TCP (for the desktop two-client demo / LAN). Binds a
  /// listener at `listen_addr` (e.g. `127.0.0.1:7001`) and uses the relay at `relay_addr`
  /// for rendezvous + offline delivery. Runs the background poll loop. (Production would
  /// use a Tor variant of this constructor.)
  static Future<NightdropCore> newNetworked(
          {required String listenAddr, required String relayAddr}) =>
      RustLib.instance.api.crateApiNightdropCoreNewNetworked(
          listenAddr: listenAddr, relayAddr: relayAddr);

  /// Real core over the **embedded Tor transport** (the production WAN path, §6): this
  /// device gets a reachable `.onion`, so two peers pair and converse over any network
  /// (LTE included) with no public IP or port-forwarding. Requires the crate built with
  /// `--features tor`; bootstrapping a circuit can take tens of seconds. QR pairing needs
  /// no relay (the QR carries the inviter's `.onion`); an optional `relay_addr` (itself
  /// reachable over Tor) would enable short-code rendezvous + offline delivery.
  /// `state_dir` is a writable base directory for Tor's state/cache — required on Android
  /// (pass the app's support directory); pass `None` on desktop for arti's defaults.
  ///
  /// When `persist_path` + `persist_key` (base64 32-byte key) are given, the device state
  /// is persisted to that encrypted file: if the file already exists it is **restored**
  /// (same identity + chats survive a restart); otherwise a fresh identity is created and
  /// saved. The key is held by the OS secure store on the Dart side. The Tor onion address
  /// itself persists separately via arti's `state_dir`.
  static Future<NightdropCore> newTor(
          {String? stateDir,
          String? relayAddr,
          String? persistPath,
          String? persistKey}) =>
      RustLib.instance.api.crateApiNightdropCoreNewTor(
          stateDir: stateDir,
          relayAddr: relayAddr,
          persistPath: persistPath,
          persistKey: persistKey);

  /// Whether this device's address is published/reachable yet. On Tor it is `false` for the
  /// ~1–3 min after launch while the onion descriptor (re)publishes — the UI shows a "still
  /// publishing, others can't pair yet" banner until this is `true`.
  Future<bool> onionReady();

  /// Open a new chat against a fresh in-process peer (demo only): stands up a real `Node`
  /// over the in-memory network and performs the genuine bundle handshake. Errors on a real
  /// core, which has no demo harness — real chats are opened by pairing (QR / short code).
  Future<Contact> openChat({String? code});

  /// Health of each of our advertised extra relays (#17), as of the last relay poll: `(address,
  /// reachable)`. A relay that stops answering our mailbox drain (e.g. a self-hosted one that
  /// went down) reports `reachable = false`, so the UI can warn the user and suggest adding a
  /// backup relay. A not-yet-polled relay reports `true` (optimistic).
  Future<List<RelayHealth>> relayHealth();

  /// Report a **screenshot** of this chat (#1) — log it locally and tell the peer.
  ///
  /// Screenshots stay allowed: blocking them just moves people to photographing the screen, which
  /// is undetectable. Making them visible is the honest trade. Fire-and-forget from the UI's point
  /// of view; a chat that no longer exists is silently ignored.
  ///
  /// Only Android 14+ can detect a screenshot, so a peer's silence proves nothing — the UI must
  /// not imply otherwise.
  Future<void> reportScreenshot({required String contactId});

  /// Restore a core from a password-encrypted backup file (§7, TODO #5). `listen_addr` +
  /// `relay_addr` select the real networked transport (as in [`new_networked`]); omit
  /// both for the in-process demo. Runs the background poll loop.
  static Future<NightdropCore> restoreBackup(
          {required String path,
          required String password,
          String? listenAddr,
          String? relayAddr}) =>
      RustLib.instance.api.crateApiNightdropCoreRestoreBackup(
          path: path,
          password: password,
          listenAddr: listenAddr,
          relayAddr: relayAddr);

  /// Import a password-encrypted backup onto the **Tor transport** with persistence
  /// (§7 / logout-recovery): decrypt the backup, re-encrypt it as the at-rest state file
  /// under `persist_key`, then bootstrap Tor and restore from it (so it also survives
  /// future restarts). This is the Tor counterpart of [`restore_backup`](Self::restore_backup).
  static Future<NightdropCore> restoreBackupTor(
          {required String backupPath,
          required String password,
          String? stateDir,
          String? relayAddr,
          required String persistPath,
          required String persistKey}) =>
      RustLib.instance.api.crateApiNightdropCoreRestoreBackupTor(
          backupPath: backupPath,
          password: password,
          stateDir: stateDir,
          relayAddr: relayAddr,
          persistPath: persistPath,
          persistKey: persistKey);

  /// Recover from an opt-in **server backup** on a fresh device (§7c / #9): bootstrap Tor,
  /// fetch the opaque blob from the relay by its password-derived handle, decrypt it with the
  /// user's recovery `password`, and rebuild identity + chats — persisted under `persist_key`
  /// so it survives future restarts. The relay counterpart of [`restore_backup_tor`].
  ///
  /// The backup blob does not carry into a *pre-bootstrap* onion keystore here (the relay is
  /// only reachable once Tor is up), so this device comes back on a **new** `.onion`; the
  /// startup address-rotation announcement (#11) then tells contacts the new address. Note: the
  /// relay copy is drained on fetch, so an unsuccessful attempt (e.g. wrong password) consumes
  /// it — the same "lose the password, lose the backup" contract as create.
  static Future<NightdropCore> restoreServerBackupTor(
          {required String password,
          String? stateDir,
          required String relayAddr,
          required String persistPath,
          required String persistKey}) =>
      RustLib.instance.api.crateApiNightdropCoreRestoreServerBackupTor(
          password: password,
          stateDir: stateDir,
          relayAddr: relayAddr,
          persistPath: persistPath,
          persistKey: persistKey);

  /// The human-comparable **safety number** for a contact (12×5 digits, identical on both
  /// devices) — compare it out-of-band to confirm no MITM on pairing (key-verification design).
  Future<String> safetyNumber({required String contactId});

  /// The raw safety fingerprint (base64url) to render as a QR for scan-to-verify.
  Future<String> safetyQr({required String contactId});

  /// Write the backup prepared by [`create_backup`](Self::create_backup) to `path` (the
  /// location chosen by the user after acknowledging the password, §7 / TODO #4).
  Future<void> saveBackup({required String path});

  /// Send an image/video attachment (E2E-encrypted, sealed at rest). `kind` is
  /// "image"/"video", `mime` like "image/jpeg". Capped at 100 MB.
  Future<void> sendMedia(
      {required String contactId,
      required List<int> data,
      required String mime,
      required String kind,
      required List<int> thumb});

  /// Send a message. In demo mode the reply is produced synchronously and returned; in
  /// real mode the reply arrives asynchronously via the poll loop + event stream.
  Future<List<ChatMessage>> sendMessage(
      {required String contactId, required String text});

  /// Tell the core the app moved to/from the background. Backgrounded, the poller slows
  /// down to conserve battery/data; foregrounded, it resumes snappy polling and does an
  /// immediate relay catch-up so queued offline mail appears right away.
  Future<void> setBackground({required bool background});

  /// Set a chat's disappearing-messages timer (`secs`, 0 = off). A shared setting: messages
  /// older than the timer are deleted on both devices, and the new value is synced to the
  /// peer. Common values: 3600 (1h), 86400 (1d), 604800 (1w).
  Future<void> setDisappearing(
      {required String contactId, required BigInt secs});

  /// Give a contact a nickname that only you see (`contact-naming.md`). Never sent, so a peer
  /// can neither read it nor set it; empty clears it. This is the answer to a contact list of
  /// identical "Anon"s — the peer's own name is their choice, and may be missing or duplicated.
  Future<void> setLocalName({required String contactId, required String name});

  /// Set the local user's display name within one chat (§4).
  Future<void> setMyName({required String contactId, required String name});

  /// Replace our advertised extra relay set (#17): peers will fan out our offline mail to these
  /// too, and we poll them alongside the default. Announces the change to existing contacts
  /// (E2E) and persists. Addresses are validated as non-empty; reachability is the user's call.
  Future<void> setMyRelays({required List<String> relays});

  /// Toggle opt-in 24h server storage for a chat (§6).
  Future<void> setRemoteStorage(
      {required String contactId, required bool enabled});

  /// Set the contact's verified flag (after comparing the safety number by hand) and persist.
  Future<void> setVerified({required String contactId, required bool verified});

  /// Stop the background poller and tear down the network side (see
  /// [`crate::node::Node::close_transport`]), releasing Tor's on-disk state lock. Idempotent;
  /// the core stays readable afterwards but can no longer send or receive.
  ///
  /// Call this before building a second core over the same `state_dir` — restoring a backup
  /// does exactly that, and arti refuses to launch a second onion service while the first
  /// instance still holds the lock. Dropping the core is **not** enough on its own: the poller
  /// thread holds its own handle on the same state and only notices the stop flag on its next
  /// tick (up to 2s later, backgrounded), so the lock would still be held when the new instance
  /// tried to start. Tearing the transport down here makes the release synchronous.
  Future<void> shutdown();

  /// Unsend ("delete for both") one of our own messages (`msg_id` from [`ChatMessage`]).
  /// Same eligibility as [`edit_message`](Self::edit_message): within 15 minutes, or while
  /// still queued (then the relay blob is recalled so the peer never receives it). The
  /// message becomes a "deleted" tombstone (`kind == "deleted"`) on both sides.
  Future<void> unsendMessage(
      {required String contactId, required String msgId});

  /// Compare a scanned safety-QR payload against this contact; on a match, mark verified and
  /// persist. Returns whether it matched.
  Future<bool> verifySafetyQr(
      {required String contactId, required String scanned});
}

/// A push event from the core to the UI (flutter_rust_bridge stream). The real transport
/// uses this to surface unsolicited messages and incoming requests; the UI reacts by
/// re-reading state. `kind` is one of "request", "message", "contacts".
///
/// `contacts` names the chats whose **message history** actually changed, so the UI can re-pull
/// only those instead of every conversation (§1.5.5). Empty means "unknown / refresh broadly" —
/// e.g. roster changes (the contact/request lists are cheap to re-read) or control-frame churn
/// whose affected chat isn't individually tracked.
class AppEvent {
  final String kind;
  final List<String> contacts;

  const AppEvent({
    required this.kind,
    required this.contacts,
  });

  @override
  int get hashCode => kind.hashCode ^ contacts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          contacts == other.contacts;
}

/// One message in a conversation (UI-facing).
class ChatMessage {
  final bool fromMe;
  final String text;

  /// A local system notice (deletion/approval) rather than an exchanged message. The UI
  /// renders these centered, without a sender name or bubble side.
  final bool system;

  /// Message kind: "text" (default), "image", or "video". For media, `text` is empty and
  /// the bytes live in a sealed file fetched via [`media_bytes`](NightdropCore::media_bytes).
  final String kind;

  /// MIME type for a media message (e.g. "image/png", "video/mp4"); empty for text.
  final String mime;

  /// Opaque id of the sealed media file for this message; empty for text. For a video
  /// still in transit this is empty (the bytes haven't arrived yet) — see `thumb_id`.
  final String mediaId;

  /// Size of the media in bytes (for display); 0 for text.
  final BigInt mediaSize;

  /// Correlates a `MediaIncoming` placeholder with its later `Media` payload.
  final String transferId;

  /// Sealed-file id of a small preview thumbnail (videos); empty if none. While a video is
  /// in transit, the UI shows this with a spinner until `media_id` is filled.
  final String thumbId;

  /// Delivery state of an outgoing (`from_me`) message: "" (n/a — incoming/system),
  /// "sent" (handed to the peer directly), "queued" (held on the relay until they're
  /// online), "delivered" (the peer has since been seen online), or "expired" (sat
  /// queued past the relay's 24h TTL without an ack — never delivered, §11.3).
  final String delivery;

  /// Random per-message token shared by both sides (rides inside the wire frame), so an
  /// [`edit_message`](NightdropCore::edit_message) can name its target. Empty for system
  /// notices and messages that predate editing.
  final String msgId;

  /// True once the text was replaced by a sender edit — the UI shows an "edited" tag.
  final bool edited;

  /// Unix timestamp (seconds) when this message was created locally (sent) or received.
  /// Drives the edit window, the "expired" badge, and the ephemeral-chat time-bomb.
  /// 0 for messages persisted before timestamps existed (they never expire/edit).
  final BigInt at;

  const ChatMessage({
    required this.fromMe,
    required this.text,
    required this.system,
    required this.kind,
    required this.mime,
    required this.mediaId,
    required this.mediaSize,
    required this.transferId,
    required this.thumbId,
    required this.delivery,
    required this.msgId,
    required this.edited,
    required this.at,
  });

  @override
  int get hashCode =>
      fromMe.hashCode ^
      text.hashCode ^
      system.hashCode ^
      kind.hashCode ^
      mime.hashCode ^
      mediaId.hashCode ^
      mediaSize.hashCode ^
      transferId.hashCode ^
      thumbId.hashCode ^
      delivery.hashCode ^
      msgId.hashCode ^
      edited.hashCode ^
      at.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          fromMe == other.fromMe &&
          text == other.text &&
          system == other.system &&
          kind == other.kind &&
          mime == other.mime &&
          mediaId == other.mediaId &&
          mediaSize == other.mediaSize &&
          transferId == other.transferId &&
          thumbId == other.thumbId &&
          delivery == other.delivery &&
          msgId == other.msgId &&
          edited == other.edited &&
          at == other.at;
}

/// A 1:1 conversation partner. Names default to "Anon" and are per-chat (§4).
class Contact {
  final String id;
  final String theirName;
  final String myName;
  final bool remoteStorage;

  /// Per-chat disappearing-messages timer in seconds (0 = off). A shared setting: changing
  /// it is synced to the peer so both devices delete messages older than this horizon.
  final BigInt disappearingSecs;

  /// Whether **we** have this chat in a backup (#7). Drives the logout signal: an un-backed
  /// chat's peer is told the chat is closed on identity deletion (§11.6). UI can badge it.
  final bool backedUp;

  /// Whether the **peer** told us they keep a (Full) backup of this chat (#7) — a transparency
  /// signal; the UI shows a persistent warning that our messages may persist in their backup.
  final bool peerBackedUp;

  /// Whether the user has **verified the safety number** for this contact out-of-band
  /// (key-verification design). Per-identity-key, so a re-paired contact starts unverified.
  final bool verified;

  /// Whether the **peer** told us *they* verified this chat's safety number — **informational
  /// only**: the UI shows "the other person marked this verified", but it never sets our own
  /// `verified`. Each side must still confirm the number itself, so a compromised device can't
  /// forge a verified badge on the other. Resets on a re-pair (new session), like `verified`.
  final bool peerVerified;

  /// The peer's advertised **extra** relay addresses (#17): where their mailbox also lives, so
  /// our offline mail to them is fanned out redundantly. The shared primary relay is implicit.
  final List<String> peerRelays;

  /// Whether opt-in server storage (§6) is actually working: `false` when it is enabled but the
  /// last send couldn't reach any relay to store the copy (the message still reached the peer
  /// directly). Lets the UI downgrade the storage banner to "not currently stored" instead of
  /// implying a server copy exists. Always `true` when server storage is off. Ephemeral.
  final bool remoteStorageHealthy;

  /// Unix seconds of the last **authenticated** contact from this peer — a message we decrypted
  /// or a control frame that verified on their ratchet, including the silent delivery `Ack` that
  /// says their device drained our mailbox. `0` when we have no reading yet.
  ///
  /// A nickname **you** gave this contact, or empty. Local only: it is never sent, never
  /// announced, and never leaves the device — only you know that this key is the person you met,
  /// and the peer cannot supply that knowledge. Takes precedence over `their_name` in the UI.
  final String localName;

  /// Six characters derived from this contact's identity key, to tell two unnamed contacts apart
  /// (`docs/design/contact-naming.md`). **Not verification** — it is short enough to grind, so a
  /// matching tag proves nothing and the UI must never let it look like the safety number does.
  /// Derived rather than random so it *changes* when the identity does.
  final String identityTag;

  /// Drives the "no sign of them" notice. It reports **silence, not a cause**: a wiped identity,
  /// a seized phone, a lost phone and a flat battery all look the same from here, and the UI must
  /// not imply otherwise. That ambiguity is deliberate — see `docs/design/silence-detection.md`.
  final BigInt lastSeenSecs;

  const Contact({
    required this.id,
    required this.theirName,
    required this.myName,
    required this.remoteStorage,
    required this.disappearingSecs,
    required this.backedUp,
    required this.peerBackedUp,
    required this.verified,
    required this.peerVerified,
    required this.peerRelays,
    required this.remoteStorageHealthy,
    required this.localName,
    required this.identityTag,
    required this.lastSeenSecs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      theirName.hashCode ^
      myName.hashCode ^
      remoteStorage.hashCode ^
      disappearingSecs.hashCode ^
      backedUp.hashCode ^
      peerBackedUp.hashCode ^
      verified.hashCode ^
      peerVerified.hashCode ^
      peerRelays.hashCode ^
      remoteStorageHealthy.hashCode ^
      localName.hashCode ^
      identityTag.hashCode ^
      lastSeenSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Contact &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          theirName == other.theirName &&
          myName == other.myName &&
          remoteStorage == other.remoteStorage &&
          disappearingSecs == other.disappearingSecs &&
          backedUp == other.backedUp &&
          peerBackedUp == other.peerBackedUp &&
          verified == other.verified &&
          peerVerified == other.peerVerified &&
          peerRelays == other.peerRelays &&
          remoteStorageHealthy == other.remoteStorageHealthy &&
          localName == other.localName &&
          identityTag == other.identityTag &&
          lastSeenSecs == other.lastSeenSecs;
}

/// An anonymous, device-held identity handle (just its public id for the UI).
class Identity {
  final String id;

  const Identity({
    required this.id,
  });

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Identity && runtimeType == other.runtimeType && id == other.id;
}

/// A pairing invite shown to the other person (§5). `short_code` is the Wormhole-style
/// `slot-secret-words`; `qr_payload` embeds the inviter's address + a real pre-key bundle.
class PairingInvite {
  final String shortCode;
  final String qrPayload;

  const PairingInvite({
    required this.shortCode,
    required this.qrPayload,
  });

  @override
  int get hashCode => shortCode.hashCode ^ qrPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingInvite &&
          runtimeType == other.runtimeType &&
          shortCode == other.shortCode &&
          qrPayload == other.qrPayload;
}

/// Reachability of one of our advertised extra relays (#17), for the UI's relay-status surface.
class RelayHealth {
  /// The relay address we advertise (as entered by the user; `.onion` or host:port).
  final String address;

  /// Whether it answered our mailbox drain on the last poll. `false` = likely offline.
  final bool reachable;

  const RelayHealth({
    required this.address,
    required this.reachable,
  });

  @override
  int get hashCode => address.hashCode ^ reachable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelayHealth &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          reachable == other.reachable;
}

/// The result of enabling an opt-in server backup (§7c). `password` is the randomly generated
/// recovery secret — shown **once**, never persisted; it is the only way to restore, and the
/// relay never receives it (it holds an opaque blob addressed by a password-derived handle).
/// `expires_at_secs` is the exact Unix time the server copy is dropped, for the acknowledgment
/// screen the invariant requires.
class ServerBackupInfo {
  final String password;
  final BigInt expiresAtSecs;

  const ServerBackupInfo({
    required this.password,
    required this.expiresAtSecs,
  });

  @override
  int get hashCode => password.hashCode ^ expiresAtSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerBackupInfo &&
          runtimeType == other.runtimeType &&
          password == other.password &&
          expiresAtSecs == other.expiresAtSecs;
}

/// What a secret presented at the lock screen turned out to be.
class StoreUnlock {
  /// The **duress** secret (#3) was presented: the caller must wipe the identity, and `key_b64`
  /// is empty. Never true and non-empty at once — the duress secret yields no key, ever.
  final bool duress;

  /// The store key, base64, when this was the normal secret.
  final String keyB64;

  const StoreUnlock({
    required this.duress,
    required this.keyB64,
  });

  @override
  int get hashCode => duress.hashCode ^ keyB64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoreUnlock &&
          runtimeType == other.runtimeType &&
          duress == other.duress &&
          keyB64 == other.keyB64;
}
