#!/usr/bin/env bash
# Serve the Night Drop website as a Tor v3 onion service, for local testing in Tor Browser.
#
# It runs a localhost-only static file server over website/ and puts a tor hidden service in
# front of it. Nothing is exposed on your LAN — the HTTP server binds 127.0.0.1 only, and the
# only reachable endpoint is the .onion (which you control).
#
# Requires the tor daemon:   sudo dnf install -y tor
#
# Usage:
#   scripts/onion-website.sh [PORT]
#     PORT          local HTTP port the site is served on (default 8787)
#
# Env:
#   ONION_STATE     dir holding the tor data + the onion key
#                   (default: ~/.local/share/nightdrop-website-onion)
#
# The onion key persists in ONION_STATE, so the .onion address stays the same across restarts.
# Keep that directory private (it holds the service's secret key). Ctrl-C stops both processes.

set -euo pipefail

PORT="${1:-8787}"
STATE="${ONION_STATE:-$HOME/.local/share/nightdrop-website-onion}"
# Localhost-only SOCKS port for the self-dial watchdog (see the torrc below).
SOCKS_PORT="${ONION_SOCKS_PORT:-9063}"
# How often to prove reachability end to end, and how many consecutive failures count as dark.
# A restart is not free — it rotates the introduction points, and clients hold the old descriptor
# until they refetch — so the default waits ~15 minutes of sustained darkness before spending one.
PROBE_INTERVAL="${ONION_PROBE_INTERVAL:-300}"
DARK_LIMIT="${ONION_DARK_LIMIT:-3}"
# What the probe fetches. Deliberately the file the app depends on for update checks, so the
# watchdog proves the thing that actually matters rather than merely that tor answered.
PROBE_PATH="${ONION_PROBE_PATH:-/update.json}"
# Below this, a failed dial is treated as INCONCLUSIVE rather than dark. Reaching a genuinely
# unreachable onion takes many seconds — fetching the descriptor from the HSDirs, then trying
# introduction points — so a dial that gives up in a heartbeat did not observe the onion at all;
# something local refused it. Counting those as darkness is what drove the restart counter to 10
# (see the 'after 0s' entries in the journal), and every one of those restarts rotated the
# introduction points and broke the clients it was meant to protect.
MIN_REAL_FAIL="${ONION_MIN_REAL_FAIL:-10}"
#
# STILL UNEXPLAINED, as of 2026-08-14: this onion goes genuinely dark for multi-minute windows,
# often. Four days of journal show 19 dials that reached the SOCKS proxy and then timed out at the
# full 120s, and every restart so far was driven by three of those in a row — real darkness, not
# the false positives the rule above removes. Meanwhile tor logs no warning at all and its
# heartbeat reports real clients arriving throughout (130, 158, 86 INTRODUCE2 cells per 6h), so
# the service is up and serving while our own probe cannot reach it.
#
# The probe shares the service's tor instance, so "our tor cannot dial our onion" and "the onion is
# unreachable" are not distinguishable from here. Separating them needs a probe on an independent
# tor client, which is what the relay watchdog does. Until that exists, a restart is treating a
# symptom whose cause is unknown — so keep the sustained-darkness bar high rather than lowering it.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd)"
WEB="$REPO/website"

if ! command -v tor >/dev/null 2>&1; then
  echo "error: the 'tor' daemon is not installed." >&2
  echo "       install it with:  sudo dnf install -y tor" >&2
  exit 1
fi
if [ ! -f "$WEB/index.html" ]; then
  echo "error: website not found at $WEB" >&2
  exit 1
fi

HS="$STATE/hs"
TORDATA="$STATE/tor-data"
mkdir -p "$HS" "$TORDATA"
# tor refuses a HiddenServiceDir that others can read.
chmod 700 "$STATE" "$HS" "$TORDATA"

TORRC="$STATE/torrc"
# A localhost SocksPort exists solely so this service can DIAL ITSELF (see the watchdog at the
# bottom). It used to be `SocksPort 0`. Reaching our own onion has to go through descriptor
# lookup, introduction points and a rendezvous exactly as a real client's does, so it is the only
# check that actually answers "can anyone reach this site" — and it needs a Tor client to do it.
# Using this instance's own means the check does not silently pass or fail on the health of some
# other tor on the box.
cat > "$TORRC" <<EOF
# Generated by scripts/onion-website.sh — do not edit; re-run the script instead.
SocksPort 127.0.0.1:$SOCKS_PORT
DataDirectory $TORDATA
HiddenServiceDir $HS
HiddenServiceVersion 3
HiddenServicePort 80 127.0.0.1:$PORT
Log notice stderr
EOF

web_pid=""
tor_pid=""
cleanup() {
  [ -n "$tor_pid" ] && kill "$tor_pid" 2>/dev/null || true
  [ -n "$web_pid" ] && kill "$web_pid" 2>/dev/null || true
}
trap cleanup INT TERM EXIT

echo "Serving $WEB on http://127.0.0.1:$PORT (localhost only) ..."
# Default: keep no logs (privacy). Opt in to request logging for a private visitor count by setting
# NIGHTDROP_ONION_LOG=/path/to/log — then `scripts/stats.sh $NIGHTDROP_ONION_LOG` summarises visits.
# Over Tor every request arrives from 127.0.0.1, so the log holds request counts, never client IPs.
if [ -n "${NIGHTDROP_ONION_LOG:-}" ]; then
  echo "  request logging ON → $NIGHTDROP_ONION_LOG (counts only; Tor gives no client identity)"
  python3 -m http.server "$PORT" --bind 127.0.0.1 --directory "$WEB" >/dev/null 2>>"$NIGHTDROP_ONION_LOG" &
else
  python3 -m http.server "$PORT" --bind 127.0.0.1 --directory "$WEB" >/dev/null 2>&1 &
fi
web_pid=$!

echo "Starting tor; publishing the onion descriptor can take ~30-60s ..."
tor -f "$TORRC" &
tor_pid=$!

HOSTFILE="$HS/hostname"
for _ in $(seq 1 90); do
  [ -f "$HOSTFILE" ] && break
  # if tor died, stop waiting
  kill -0 "$tor_pid" 2>/dev/null || break
  sleep 1
done

if [ -f "$HOSTFILE" ]; then
  ONION="$(cat "$HOSTFILE")"
  # When run under a systemd notify service, surface the address in `systemctl status`
  # (shows up as the "Status:" line) and signal readiness. No-op when run by hand.
  if [ -n "${NOTIFY_SOCKET:-}" ] && command -v systemd-notify >/dev/null 2>&1; then
    systemd-notify --ready --status="serving http://$ONION/"
  fi
  cat <<EOF

==================================================================
 Night Drop website is live on Tor:

     http://$ONION/

 Open that in Tor Browser. The first descriptor publish can take a
 minute, so if it 404s at the network level, wait and retry.
 Press Ctrl-C to stop serving.
==================================================================

EOF
else
  echo "warning: the onion hostname was not created (see tor logs above)." >&2
fi

# --- Self-dial watchdog ------------------------------------------------------------------------
#
# On 2026-08-05 this onion went unreachable for Tor Browser and for the phone while systemd
# reported the unit active and serving, and nothing in the journal said otherwise. `Restart=always`
# cannot recover that: nothing crashed. The relay had the identical failure and the identical
# fix — do not trust a component's own account of its health, prove it end to end — so this does
# the same thing, and for the same reason.
#
# Each cycle:
#   * dial our own .onion through our own SocksPort. That exercises descriptor lookup, intro
#     points and rendezvous, which is what a real visitor does and what silently breaks.
#   * on success, log a heartbeat. Every cycle, deliberately: it is the only line proving the site
#     was reachable at a given moment, and every other number here is worthless without evidence
#     that the log is still growing. An onion nobody visits leaves no other trace.
#   * on failure, corroborate against the local HTTP server before blaming the onion layer. If the
#     static server is the thing that died, that is a different fault with the same symptom.
#
# Known limitation, stated rather than papered over: a local network outage is indistinguishable
# from a dark onion here, so it will eventually trigger a restart. That is cheap compared with the
# failure this exists to catch — but it is why the threshold is sustained failure and not one miss.
if [ -f "$HOSTFILE" ]; then
  ONION="$(cat "$HOSTFILE")"
  echo "watchdog: self-dialling http://$ONION$PROBE_PATH every ${PROBE_INTERVAL}s (dark after $DARK_LIMIT)" >&2
fi

fails=0
elapsed=0
while :; do
  sleep 10
  # Supervise the two children at a finer granularity than the probe interval, so a crash is
  # noticed in seconds rather than minutes.
  if ! kill -0 "$tor_pid" 2>/dev/null; then
    echo "nightdrop-onion: tor exited — leaving so systemd restarts us" >&2
    exit 1
  fi
  if ! kill -0 "$web_pid" 2>/dev/null; then
    echo "nightdrop-onion: static file server exited — leaving so systemd restarts us" >&2
    exit 1
  fi

  elapsed=$((elapsed + 10))
  [ "$elapsed" -ge "$PROBE_INTERVAL" ] || continue
  elapsed=0
  [ -n "${ONION:-}" ] || continue

  began=$(date +%s)
  code="$(curl -s -o /dev/null -w '%{http_code}' \
      --socks5-hostname "127.0.0.1:$SOCKS_PORT" --max-time 120 \
      "http://$ONION$PROBE_PATH" 2>/dev/null || true)"
  took=$(( $(date +%s) - began ))

  # Any HTTP status at all means the onion is REACHABLE: the descriptor was found, an intro point
  # answered and the rendezvous completed. Only curl returning no response (000) is darkness.
  # Conflating the two would restart the service every cycle over a missing file — a content
  # problem that republishing the descriptor cannot fix, and that a restart makes worse by
  # rotating the introduction points.
  if [ -n "$code" ] && [ "$code" != 000 ]; then
    if [ "$code" = 200 ]; then
      echo "nightdrop-onion: self-dial reached in ${took}s" >&2
    else
      echo "nightdrop-onion: self-dial reached in ${took}s but $PROBE_PATH returned $code — the onion is fine, the site is not serving that file" >&2
    fi
    fails=0
    continue
  fi

  if ! curl -s -o /dev/null --max-time 5 "http://127.0.0.1:$PORT$PROBE_PATH" 2>/dev/null; then
    echo "nightdrop-onion: the local server stopped answering on 127.0.0.1:$PORT — restarting" >&2
    exit 1
  fi

  # A failure only counts as darkness if the probe was actually in a position to observe it.
  # Two ways it was not, and neither says anything about whether clients can reach us:
  #
  #   * the SOCKS port is not accepting — tor is still starting, or has gone away. The probe never
  #     left the box.
  #   * the dial failed faster than a real one can. A dark onion is discovered slowly (HSDir fetch,
  #     then introduction attempts); an instant 000 is a local refusal wearing the same clothes.
  #
  # This is the same mistake the relay watchdog made in its own way: evidence must be attributable
  # to the thing being judged before it is spent on a restart.
  if ! timeout 3 bash -c "cat < /dev/null > /dev/tcp/127.0.0.1/$SOCKS_PORT" 2>/dev/null; then
    echo "nightdrop-onion: self-dial could not start — SOCKS $SOCKS_PORT is not accepting; tor is starting or gone. Inconclusive, not counted (still ${fails}/${DARK_LIMIT})" >&2
    continue
  fi
  if [ "$took" -lt "$MIN_REAL_FAIL" ]; then
    echo "nightdrop-onion: self-dial failed in ${took}s, faster than a real unreachable onion — treating as a local hiccup, not darkness (still ${fails}/${DARK_LIMIT})" >&2
    continue
  fi

  fails=$((fails + 1))
  echo "nightdrop-onion: self-dial FAILED (${fails}/${DARK_LIMIT}, http='${code:-none}' after ${took}s); the local server is fine, so the onion layer is dark" >&2
  if [ "$fails" -ge "$DARK_LIMIT" ]; then
    echo "nightdrop-onion: dark for ~$((fails * PROBE_INTERVAL))s — exiting so systemd republishes the descriptor" >&2
    exit 1
  fi
done
