#!/usr/bin/env bash
# Serve the Night Drop website as a Tor v3 onion service, for local testing in Tor Browser.
#
# It runs a localhost-only static file server over website/ and puts a tor hidden service in
# front of it. Nothing is exposed on your LAN — the HTTP server binds 127.0.0.1 only, and the
# only reachable endpoint is the .onion (which you control).
#
# Requires the tor daemon:   sudo dnf install -y tor
#
# Usage:
#   scripts/onion-website.sh [PORT]
#     PORT          local HTTP port the site is served on (default 8787)
#
# Env:
#   ONION_STATE     dir holding the tor data + the onion key
#                   (default: ~/.local/share/nightdrop-website-onion)
#
# The onion key persists in ONION_STATE, so the .onion address stays the same across restarts.
# Keep that directory private (it holds the service's secret key). Ctrl-C stops both processes.

set -euo pipefail

PORT="${1:-8787}"
STATE="${ONION_STATE:-$HOME/.local/share/nightdrop-website-onion}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd)"
WEB="$REPO/website"

if ! command -v tor >/dev/null 2>&1; then
  echo "error: the 'tor' daemon is not installed." >&2
  echo "       install it with:  sudo dnf install -y tor" >&2
  exit 1
fi
if [ ! -f "$WEB/index.html" ]; then
  echo "error: website not found at $WEB" >&2
  exit 1
fi

HS="$STATE/hs"
TORDATA="$STATE/tor-data"
mkdir -p "$HS" "$TORDATA"
# tor refuses a HiddenServiceDir that others can read.
chmod 700 "$STATE" "$HS" "$TORDATA"

TORRC="$STATE/torrc"
cat > "$TORRC" <<EOF
# Generated by scripts/onion-website.sh — do not edit; re-run the script instead.
SocksPort 0
DataDirectory $TORDATA
HiddenServiceDir $HS
HiddenServiceVersion 3
HiddenServicePort 80 127.0.0.1:$PORT
Log notice stderr
EOF

web_pid=""
tor_pid=""
cleanup() {
  [ -n "$tor_pid" ] && kill "$tor_pid" 2>/dev/null || true
  [ -n "$web_pid" ] && kill "$web_pid" 2>/dev/null || true
}
trap cleanup INT TERM EXIT

echo "Serving $WEB on http://127.0.0.1:$PORT (localhost only) ..."
python3 -m http.server "$PORT" --bind 127.0.0.1 --directory "$WEB" >/dev/null 2>&1 &
web_pid=$!

echo "Starting tor; publishing the onion descriptor can take ~30-60s ..."
tor -f "$TORRC" &
tor_pid=$!

HOSTFILE="$HS/hostname"
for _ in $(seq 1 90); do
  [ -f "$HOSTFILE" ] && break
  # if tor died, stop waiting
  kill -0 "$tor_pid" 2>/dev/null || break
  sleep 1
done

if [ -f "$HOSTFILE" ]; then
  ONION="$(cat "$HOSTFILE")"
  # When run under a systemd notify service, surface the address in `systemctl status`
  # (shows up as the "Status:" line) and signal readiness. No-op when run by hand.
  if [ -n "${NOTIFY_SOCKET:-}" ] && command -v systemd-notify >/dev/null 2>&1; then
    systemd-notify --ready --status="serving http://$ONION/"
  fi
  cat <<EOF

==================================================================
 Night Drop website is live on Tor:

     http://$ONION/

 Open that in Tor Browser. The first descriptor publish can take a
 minute, so if it 404s at the network level, wait and retry.
 Press Ctrl-C to stop serving.
==================================================================

EOF
else
  echo "warning: the onion hostname was not created (see tor logs above)." >&2
fi

# Keep running (serving) until tor exits or the user hits Ctrl-C.
wait "$tor_pid"
