#!/usr/bin/env sh
# Generate a Night Drop `transports.txt` from the pluggable-transport (PT) client binaries
# installed on this machine. See docs/bridges.md — the core reads `transports.txt` from the
# Tor state directory (alongside `bridges.txt`) and launches a PT on demand when a bridge
# line names it (obfs4/snowflake/…).
#
# This does NOT install anything and never runs the binaries — it only detects what's on
# PATH and writes their absolute paths. Install the PTs from your distro or the Tor project
# first (e.g. `obfs4proxy`/`lyrebird`, `snowflake-client`).
#
# Usage:
#   scripts/setup-pluggable-transports.sh [OUTPUT_PATH]
#
#   OUTPUT_PATH  Where to write transports.txt (default: ./transports.txt). Copy the result
#                into Night Drop's Tor state directory (the one containing arti-state/).
#
# Exit status: 0 if at least one PT was found and written, 1 if none were found.

set -eu

OUT="${1:-./transports.txt}"

# Map a binary name to the transport protocol(s) it provides. lyrebird is the maintained
# successor to obfs4proxy; both speak obfs4 + meek_lite. Order matters: prefer lyrebird.
#   "binary:protocols"
CANDIDATES="lyrebird:obfs4,meek_lite obfs4proxy:obfs4,meek_lite snowflake-client:snowflake meek-client:meek"

# Avoid registering the same protocol twice (e.g. if both lyrebird and obfs4proxy exist).
seen_protocols=""
lines=""
found=0

for entry in $CANDIDATES; do
    bin=${entry%%:*}
    protos=${entry#*:}

    path=$(command -v "$bin" 2>/dev/null || true)
    [ -n "$path" ] || continue

    # Skip if every protocol this binary offers is already covered by an earlier one.
    novel=""
    for p in $(echo "$protos" | tr ',' ' '); do
        case " $seen_protocols " in
            *" $p "*) ;;                       # already have it
            *) novel="${novel:+$novel,}$p"; seen_protocols="$seen_protocols $p" ;;
        esac
    done
    [ -n "$novel" ] || continue

    lines="${lines}${novel} ${path}
"
    found=1
    echo "found: $novel -> $path" >&2
done

if [ "$found" -eq 0 ]; then
    cat >&2 <<'EOF'
No pluggable-transport clients found on PATH.

Install one, then re-run:
  - obfs4 / meek_lite:  your distro's `obfs4proxy` or `lyrebird`
  - snowflake:          `snowflake-client` (Tor project)

Get bridge lines for bridges.txt from https://bridges.torproject.org/ (choose obfs4).
EOF
    exit 1
fi

{
    echo "# Night Drop pluggable transports — generated by scripts/setup-pluggable-transports.sh"
    echo "# on $(date -u '+%Y-%m-%dT%H:%M:%SZ'). One '<protocols> <path>' per line; see docs/bridges.md."
    printf '%s' "$lines"
} > "$OUT"

echo "wrote $OUT — copy it into Night Drop's Tor state dir (alongside bridges.txt), then restart." >&2
